# Lab Sharks

Primero importamos librerias y los datos.

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
sharks = pd.read_csv('attacks.csv', encoding='latin1')
df = sharks.copy()
df.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN

In [3]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25723 entries, 0 to 25722
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Case Number             8702 non-null   object
 1   Date                    6302 non-null   object
 2   Year                    6300 non-null   float64
 3   Type                    6298 non-null   object
 4   Country                 6252 non-null   object
 5   Area                    5847 non-null   object
 6   Location                5762 non-null   object
 7   Activity                5758 non-null   object
 8   Name                    6092 non-null   object
 9   Sex                     5737 non-null   object
 10  Age                     3471 non-null   object
 11  Injury                  6274 non-null   object
 12  Fatal (Y/N)             5763 non-null   object
 13  Time                    2948 non-null   object
 14  Species                 3464 non-null   object
 15  Investigator or Source  6285 non-null   object
 16  pdf                     6302 non-null   object
 17  href formula            6301 non-null   object
 18  href                    6302 non-null   object
 19  Case Number.1           6302 non-null   object
 20  Case Number.2           6302 non-null   object
 21  original order          6309 non-null   float64
 22  Unnamed: 22             1 non-null      object
 23  Unnamed: 23             2 non-null      object
dtypes: float64(2), object(22)
memory usage: 22.8 MB

In [4]:
df.describe(include='object').T #ESTO ES LO CATEGORICO

,count,unique,top,freq
Case Number,8702,6287,0,2400
Date,6302,5433,1957,11
Type,6298,8,Unprovoked,4595
Country,6252,212,USA,2229
Area,5847,825,Florida,1037
Location,5762,4108,"New Smyrna Beach, Volusia County",163
Activity,5758,1532,Surfing,971
Name,6092,5230,male,550
Sex,5737,6,M,5094
Age,3471,157,17,154
Injury,6274,3737,FATAL,802
Fatal (Y/N),5763,8,N,4293
Time,2948,366,Afternoon,187
Species,3464,1549,White shark,163
Investigator or Source,6285,4969,"C. Moore, GSAF",105
pdf,6302,6291,1923.00.00.a-NJ fisherman.pdf,2
href formula,6301,6290,http://sharkattackfile.net/spreadsheets/pdf_di...,2
href,6302,6285,http://sharkattackfile.net/spreadsheets/pdf_di...,4
Case Number.1,6302,6285,1920.00.00.b,2
Case Number.2,6302,6286,1920.00.00.b,2
Unnamed: 22,1,1,stopped here,1
Unnamed: 23,2,2,Teramo,1

In [5]:
df.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

In [6]:
df.columns = [c.lower().replace('_', ' ') for c in df.columns] #con esto ponemos todo en minusculas y reemplazamos las _ por espacio, son buenas practicas

In [7]:
df.columns = df.columns.str.strip() # Ahora eliminamos espacios en blanco al principio y al final de los nombres de las columnas

In [8]:
df.columns

Index(['case number', 'date', 'year', 'type', 'country', 'area', 'location',
       'activity', 'name', 'sex', 'age', 'injury', 'fatal (y/n)', 'time',
       'species', 'investigator or source', 'pdf', 'href formula', 'href',
       'case number.1', 'case number.2', 'original order', 'unnamed: 22',
       'unnamed: 23'],
      dtype='object')

In [9]:
df.count()   # vemos los valores NO nulos

case number               8702
date                      6302
year                      6300
type                      6298
country                   6252
area                      5847
location                  5762
activity                  5758
name                      6092
sex                       5737
age                       3471
injury                    6274
fatal (y/n)               5763
time                      2948
species                   3464
investigator or source    6285
pdf                       6302
href formula              6301
href                      6302
case number.1             6302
case number.2             6302
original order            6309
unnamed: 22                  1
unnamed: 23                  2
dtype: int64

In [10]:
df.iloc[0] #primera fila, iloc funciona por indice, es decir , por posicion

case number                                                      2018.06.25
date                                                            25-Jun-2018
year                                                                 2018.0
type                                                                Boating
country                                                                 USA
area                                                             California
location                                        Oceanside, San Diego County
activity                                                           Paddling
name                                                            Julie Wolfe
sex                                                                       F
age                                                                      57
injury                    No injury to occupant, outrigger canoe and pad...
fatal (y/n)                                                               N
time                                                                  18h00
species                                                         White shark
investigator or source                                     R. Collier, GSAF
pdf                                                    2018.06.25-Wolfe.pdf
href formula              http://sharkattackfile.net/spreadsheets/pdf_di...
href                      http://sharkattackfile.net/spreadsheets/pdf_di...
case number.1                                                    2018.06.25
case number.2                                                    2018.06.25
original order                                                       6303.0
unnamed: 22                                                             NaN
unnamed: 23                                                             NaN
Name: 0, dtype: object

In [11]:
columnas_a_eliminar = ['unnamed: 22', 'unnamed: 23']
df.drop(columns=columnas_a_eliminar, inplace=True)
#Por ahora no elimino nada, sobreesribo el data frame

In [12]:
#df.set_index('country').head()  # establecer indice 

"""El método set_index en pandas se utiliza para establecer una o más columnas como el índice del DataFrame. 
El índice es una etiqueta que se utiliza para identificar y acceder a las filas en un DataFrame. 
Puedes usar set_index para cambiar el índice actual por una o más columnas de datos en tu DataFrame. 
keys: Puedes proporcionar una sola columna o una lista de columnas que deseas usar como índice. 
Si proporcionas una lista, se utilizarán múltiples columnas como índice jerárquico (índice múltiple).

inplace: Es un parámetro opcional que, si se establece en True, modificará el DataFrame original. Si se establece en False o no se proporciona, se creará un nuevo DataFrame con el índice modificado y se mantendrá el DataFrame original sin cambios.
"""

'El método set_index en pandas se utiliza para establecer una o más columnas como el índice del DataFrame. \nEl índice es una etiqueta que se utiliza para identificar y acceder a las filas en un DataFrame. \nPuedes usar set_index para cambiar el índice actual por una o más columnas de datos en tu DataFrame. \nkeys: Puedes proporcionar una sola columna o una lista de columnas que deseas usar como índice. \nSi proporcionas una lista, se utilizarán múltiples columnas como índice jerárquico (índice múltiple).\n\ninplace: Es un parámetro opcional que, si se establece en True, modificará el DataFrame original. Si se establece en False o no se proporciona, se creará un nuevo DataFrame con el índice modificado y se mantendrá el DataFrame original sin cambios.\n'

In [13]:
#df.loc[0, "pdf"] #asi reescribo una palabra dentro de una tabla

In [12]:
nan_cols = df.isna().sum() #Vamos a ver todos los elements nulos que tenemos 

nan_cols[nan_cols>0]

case number               17021
date                      19421
year                      19423
type                      19425
country                   19471
area                      19876
location                  19961
activity                  19965
name                      19631
sex                       19986
age                       22252
injury                    19449
fatal (y/n)               19960
time                      22775
species                   22259
investigator or source    19438
pdf                       19421
href formula              19422
href                      19421
case number.1             19421
case number.2             19421
original order            19414
dtype: int64

In [13]:
df.duplicated().sum()  #Duplicados del DataFrame

19411

In [14]:
filas_nulas = df[df.isna().all(axis=1)] # Seleccionar las filas donde todos los valores son nulos

# Seleccionar las filas donde al menos un valor es nulo
# filas_con_al_menos_un_nulo = df[df.isna().any(axis=1)]  IMPORTANTE

In [15]:
df.dropna(how='all', inplace=True) #elimino las filas donde todos los valores son nulos 
df.shape

(8703, 22)

In [16]:
nan_cols = df.isna().sum() # suma de elemento nulos  

nan_cols

case number                  1
date                      2401
year                      2403
type                      2405
country                   2451
area                      2856
location                  2941
activity                  2945
name                      2611
sex                       2966
age                       5232
injury                    2429
fatal (y/n)               2940
time                      5755
species                   5239
investigator or source    2418
pdf                       2401
href formula              2402
href                      2401
case number.1             2401
case number.2             2401
original order            2394
dtype: int64

In [17]:
df[df['case number'].isna()] #buscamos el nulo

,case number,date,year,type,country,area,location,activity,name,sex,...,fatal (y/n),time,species,investigator or source,pdf,href formula,href,case number.1,case number.2,original order
5488,NaN,Reported 06-Sep-1905,1905.0,Provoked,USA,Florida,"Fort Pierce, St Lucie County",Fishing,David Curry,M,...,N,NaN,NaN,"Muncie Evening Press, 8/6/1913",1905.09.06.R-Curry.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1905.09.06.R,1905.09.06.R,815.0

In [18]:
df.loc[5488, "case number"] = '1905.09.06' # lo corregimos 
df.loc[5488]

case number                                                      1905.09.06
date                                                   Reported 06-Sep-1905
year                                                                 1905.0
type                                                               Provoked
country                                                                 USA
area                                                                Florida
location                                       Fort Pierce, St Lucie County
activity                                                            Fishing
name                                                            David Curry
sex                                                                       M
age                                                                     NaN
injury                    Lacerations to leg from hooked shark PROVOKED ...
fatal (y/n)                                                               N
time                                                                    NaN
species                                                                 NaN
investigator or source                       Muncie Evening Press, 8/6/1913
pdf                                                  1905.09.06.R-Curry.pdf
href formula              http://sharkattackfile.net/spreadsheets/pdf_di...
href                      http://sharkattackfile.net/spreadsheets/pdf_di...
case number.1                                                  1905.09.06.R
case number.2                                                  1905.09.06.R
original order                                                        815.0
Name: 5488, dtype: object

In [19]:
df['case number'].duplicated().sum()        #Duplicados de la serie

2415

In [20]:
df['case number'] = df['case number'].apply(lambda x: None if x == 0 else x) #cambio los ceros por nulos, asi consigo filas de todo nulos

In [21]:
df['case number'].dtype #al no funcionar lo anterior, comprobamos el tipo de dato, ya que debería ser del tipo numérico (int o float).

dtype('O')

In [22]:
df['case number'] = df['case number'].replace('0', None) #Resulta que es de tipo objeto, asi que hago lo siguiente

In [23]:
df.dropna(how='all', inplace=True) #y ahora si, elimino las filas donde todos los valores son nulos 
df.shape

(6310, 22)

In [24]:
nan_cols = df.isna().sum() # suma de elemento nulos  

nan_cols

case number                  7
date                         8
year                        10
type                        12
country                     58
area                       463
location                   548
activity                   552
name                       218
sex                        573
age                       2839
injury                      36
fatal (y/n)                547
time                      3362
species                   2846
investigator or source      25
pdf                          8
href formula                 9
href                         8
case number.1                8
case number.2                8
original order               1
dtype: int64

In [25]:
df[df['date'].isna()] #buscamos el nulo

,case number,date,year,type,country,area,location,activity,name,sex,...,fatal (y/n),time,species,investigator or source,pdf,href formula,href,case number.1,case number.2,original order
6302,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6304.0
6303,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6305.0
6304,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6306.0
6305,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6307.0
6306,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6308.0
6307,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6309.0
6308,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6310.0
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
df.drop(25722, inplace=True) #elimino el nulo en date

In [29]:
df.drop([6302, 6303, 6304, 6305, 6306, 6307, 6308], inplace=True)

In [30]:
nan_cols = df.isna().sum() # suma de elemento nulos  

nan_cols

case number                  0
date                         0
year                         2
type                         4
country                     50
area                       455
location                   540
activity                   544
name                       210
sex                        565
age                       2831
injury                      28
fatal (y/n)                539
time                      3354
species                   2838
investigator or source      17
pdf                          0
href formula                 1
href                         0
case number.1                0
case number.2                0
original order               0
dtype: int64

In [31]:
df[df['year'].isna()] #buscamos el nulo en year

,case number,date,year,type,country,area,location,activity,name,sex,...,fatal (y/n),time,species,investigator or source,pdf,href formula,href,case number.1,case number.2,original order
187,2017.01.08.R,Reported 08-Jan-2017,NaN,Invalid,AUSTRALIA,Queensland,NaN,Spearfishing,Kerry Daniel,M,...,NaN,NaN,Bull shark,Liquid Vision 1/8/2017,2017.01.08.R-KerryDaniel.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.01.08.R,2017.01.08.R,6116.0
6079,1836.08.19.R,Reported 19-Aug-1836,NaN,Unprovoked,ENGLAND,Cumberland,Whitehaven,Swimming,a boy,M,...,Y,NaN,NaN,"C. Moore, GSAF",1835.08.19.R-Whitehaven.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1836.08.19.R,1836.08.19.R,224.0

In [32]:
df.loc[187, "year"] = '2017' # lo corregimos 
df.loc[6079, "year"] = '1836' # lo corregimos

In [33]:
nan_cols = df.isna().sum() # suma de elemento nulos  

nan_cols

case number                  0
date                         0
year                         0
type                         4
country                     50
area                       455
location                   540
activity                   544
name                       210
sex                        565
age                       2831
injury                      28
fatal (y/n)                539
time                      3354
species                   2838
investigator or source      17
pdf                          0
href formula                 1
href                         0
case number.1                0
case number.2                0
original order               0
dtype: int64

In [34]:
df[df['type'].isna()] #buscamos el nulo en type

,case number,date,year,type,country,area,location,activity,name,sex,...,fatal (y/n),time,species,investigator or source,pdf,href formula,href,case number.1,case number.2,original order
85,2017.09.15.a,15-Sep-2017,2017.0,NaN,SAMOA,Upolu Island,Nofoalii,Fishing,male,M,...,N,Night,NaN,"Samoa Observer, 9/16/2017",2017.09.15.a-Samoa.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.15.a,2017.09.15.a,6218.0
382,2015.07.27,27-Jul-2015,2015.0,NaN,AUSTRALIA,Victoria,Tyrendarra Beach,Surfing,male,M,...,NaN,NaN,NaN,NaN,2015.07.27-Victoria.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2015.07.27,2015.07.27,5921.0
4867,1936.09.11.R,Reported 11-Sep-1936,1936.0,NaN,VIETNAM,NaN,Saigon,Wreck of a sampam,8 crew,M,...,Y,NaN,NaN,"Lansing State Journal, 9/11/1936",1936.09.11-Saigon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1936.09.11.R,1936.09.11.R,1436.0
5705,1890.03.03.R,Reported 03-Mar-1890,1890.0,NaN,CEYLON,NaN,NaN,Diving,a pearl diver,M,...,Y,NaN,NaN,"The Guardian, 3/3/1890",1890.03.03.R-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1890.03.03.R,1890.03.03.R,598.0

In [35]:
df.loc[85, "type"] = 'unknown' # lo corregimos 
df.loc[382, "type"] = 'unknown' # lo corregimos 
df.loc[4867, "type"] = 'unknown' # lo corregimos 
df.loc[5705, "type"] = 'unknown' # lo corregimos

In [36]:
nan_cols = df.isna().sum() # suma de elemento nulos  

nan_cols

case number                  0
date                         0
year                         0
type                         0
country                     50
area                       455
location                   540
activity                   544
name                       210
sex                        565
age                       2831
injury                      28
fatal (y/n)                539
time                      3354
species                   2838
investigator or source      17
pdf                          0
href formula                 1
href                         0
case number.1                0
case number.2                0
original order               0
dtype: int64

In [37]:
df[df['country'].isna()] #buscamos el nulo en country

,case number,date,year,type,country,area,location,activity,name,sex,...,fatal (y/n),time,species,investigator or source,pdf,href formula,href,case number.1,case number.2,original order
62,2017.11.13.R,Reported 13-Nov-2017,2017.0,Unprovoked,NaN,NaN,NaN,Surfing,Timur Yunusov,M,...,N,NaN,NaN,Instagram,2017.11.13.R-Timur.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.11.13.R,2017.11.13.R,6241.0
525,2014.08.00,Aug-2014,2014.0,Invalid,NaN,NaN,NaN,Sea disaster,Cuban refugees,M,...,NaN,NaN,Shark involvement not confirmed,"Associated Press, 11/27/2014",2014.08.00-Cuban-refugees.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2014.08.00,2014.08.00,5778.0
2956,1983.00.00.d,Ca. 1983,1983.0,Unprovoked,NaN,English Channel,NaN,Swimming,Padma Shri Taranath Narayan Shenoy,M,...,N,NaN,NaN,"Times of India, 2/5/2012",1983.00.00.d-Shenoy.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1983.00.00.d,1983.00.00.d,3347.0
3378,1970.11.00,Nov-1970,1970.0,Unprovoked,NaN,NaN,NaN,NaN,Heinz Plotsky,M,...,N,NaN,NaN,"H.D. Baldridge (1994), SAF Case #1645",1970.11.00-NV-Plotsky.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1970.11.00,1970.11.00,2925.0
3387,1970.08.02,02-Aug-1970,1970.0,Invalid,NaN,Caribbean Sea,Between St. Kitts & Nevis,Sea Disaster Sinking of ferryboat Christina,NaN,NaN,...,NaN,Afternoon,Shark involvement prior to death was not confi...,"Rome News Tribune, 8/3/1970",1970.08.02-Christina-ferryboat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1970.08.02,1970.08.02,2916.0
3388,1970.07.05,5-Jul-1970,1970.0,Unprovoked,NaN,NaN,NaN,NaN,male,M,...,N,Night,Mako shark,"H.D. Baldridge (1994), SAF Case #1628",1970.07.05-NV-male.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1970.07.05,1970.07.05,2915.0
3395,1970.04.00.b,Apr-1970,1970.0,Provoked,NaN,NaN,NaN,Freediving,Lionel Jarvis,M,...,N,NaN,Wobbegong shark,"H.D. Baldridge (1994), SAF Case #1616",1970.04.00.b-NV-Jarvis.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1970.04.00.b,1970.04.00.b,2908.0
3399,1970.02.05,5-Feb-1970,1970.0,Unprovoked,NaN,NaN,NaN,Wading,Sally Anne Irvine,F,...,N,NaN,Carpet shark,H.D. Baldridge (1994) SAF Case #1626,1970.02.05-NV-Irvine.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1970.02.05,1970.02.05,2904.0
3425,1969.08.00,Aug-1969,1969.0,Unprovoked,NaN,NaN,NaN,NaN,Rodney Hughes,M,...,N,NaN,NaN,H.D. Baldridge (1994) SAF Case #1602,1969.08.00-NV-Hughes.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1969.08.00,1969.08.00,2878.0
3605,1965.10.21,21-Oct-1965,1965.0,Unprovoked,NaN,NaN,Florida Strait,The boat Caribou II sank,Mario Castellanos,M,...,N,NaN,NaN,"Lodi News Sentinel, 10/30/1965",1965.10.21-Castellanos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1965.10.21,1965.10.21,2698.0
3661,1964.09.27,27-Sep-1964,1964.0,Invalid,NaN,NaN,NaN,Spearfishing,Giancarlo Griffon,M,...,NaN,11h00,Shark involvement prior to death was not confi...,C. Moore. GSAF,1964.09.27-Griffon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1964.09.27,1964.09.27,2642.0
4018,1960.01.26,26-Jan-1960,1960.0,Sea Disaster,NaN,"Between Timor & Darwin, Australia",NaN,Portuguese Airliner with 9 people aboard went ...,NaN,NaN,...,N,NaN,NaN,"V.M. Coppleson (1962), p.260",1960.01.26-Portuguese airliner.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1960.01.26,1960.01.26,2285.0
4231,1956.09.13,13-Sep-1956,1956.0,Unprovoked,NaN,Near the Andaman & Nicobar Islands,NaN,Climbing back on ship,male,M,...,Y,P.M.,Blue shark,M. Hosina,1956.09.13-TunaBoat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1956.09.13,1956.09.13,2072.0
4266,1956.00.00.g,1956,1956.0,Sea Disaster,NaN,Between Comores & Madagascar,Geyser Bank,Shipwreck,"Captain Eric Hunt, the cook & a French passenger",M,...,Y,NaN,NaN,dinofish.com,1956.00.00.g-Capt-Hunt.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1956.00.00.g,1956.00.00.g,2037.0
4498,1949.12.00.b,Dec-1949,1949.0,Sea Disaster,NaN,Caribbean Sea,Between Cuba & Costa Rica,"Sea Disaster, sinking of the motorship Wingate","Albert Battles, James Dean & 4 crew",M,...,Y,NaN,Shark involvement not confirmed,"Canberra Times, 1/6/1950",1949.12.00.b-Wingate.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1949.12.00.b,1949.12.00.b,1805.0
4639,1944.10.24,24-Oct-1944,1944.0,Sea Disaster,NaN,NaN,225 miles east of Hong Kong,Japanese POW ship Arisan Maru with 1800 Americ...,NaN,M,...,Y,>17h30,NaN,internet (multiple),1944.10.24-ArisanMaru.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1944.10.24,1944.10.24,1664.0
4700,1942.11.00.a,Nov-1942,1942.0,Sea Disaster,NaN,Off South American coast,NaN,Dutch merchant ship Zaandam torpedoed by the ...,NaN,M,...,Y,NaN,NaN,"M. Murphy; V.M. Coppleson (1962), pp.207-208",1942.11.00.a-Izzi.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1942.11.00.a,1942.11.00.a,1603.0
4712,1942.06.00,Jun-1942,1942.0,Unprovoked,NaN,300 miles east of St. Thomas (Virgin Islands),NaN,On life raft tethered to lifeboat. A seaman pu...,male,M,...,N,NaN,NaN,"V.M. Coppleson (1962), p.258",1942.06.00-on-life-raft.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1942.06.00,1942.06.00,1591.0
4726,1942.00.00.e,1942,1942.0,Sea Disaster,NaN,NaN,NaN,Jumped overboard from torpedoed Panamanian fre...,male,M,...,Y,NaN,NaN,"V.M. Coppleson (1962), p.258",1942.00.00.e-seaman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1942.00.00.e,1942.00.00.e,1577.0
4729,1942.00.00.b,1942,1942.0,Boating,NaN,NaN,NaN,"Days before the surrender of Singapore, the 3 ...","Bombardier J. Hall, Private Green of the Sherw...",M,...,N,NaN,NaN,"V.M. Coppleson (1962), p.206",1942.00.00.b-Hall-Green-Jennings.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1942.00.00.b,1942.00.00.b,1574.0
4911,1935.04.12.R,Reported 12-Apr-1935,1935.0,Unprovoked,NaN,NaN,NaN,Diving,Pearl Purdy Scott,F,...,N,NaN,NaN,"Port Arthur News, 4/12/1935",1935.04.12.R-PearlPurdyScott.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1935.04.12.R,1935.04.12.R,1392.0
5020,1931.04.27.R,Reported 27-Apr-1931,1931.0,Unprovoked,NaN,French Southern Territories,Île Saint-Paul,"Fishing, boat capsized",Quillezic,M,...,Y,NaN,NaN,"Los Angeles Times, 4/27/1931",1931.04.27.R-Quillezic.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1931.04.27.R,1931.04.27.R,1283.0
5060,1929.12.09.R,Reported 09-Dec-1929,1929.0,Unprovoked,NaN,NaN,NaN,NaN,Thomas Duggan,M,...,Y,NaN,NaN,"The Age, 12/9/1929",1929.12.09.R-Duggan.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1929.12.09.R,1929.12.09.R,1243.0
5425,1909.01.17,17-Jan-1909,1909.0,Invalid,NaN,NaN,Near the equator,Jumped overboard,Thomas Butler,M,...,NaN,NaN,Questionable,"Star, 3/18/1909",1909.01.17-Butler.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1909.01.17,1909.01.17,878.0
5586,1898.09.19.b.R,Reported 19-Sep-1898,1898.0,Unprovoked,NaN,NaN,NaN,Diving,Halletts,M,...,N,NaN,NaN,"Lincoln Evening News & Daily Call, 9/19/1898",1898.09.19.b.R-Halletts.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1898.09.19.b.R,1898.09.19.b.R,717.0
5587,1898.09.19.a.R,Reported 19-Sep-1898,1898.0,Unprovoked,NaN,NaN,NaN,Diving,male,M,...,N,NaN,NaN,"Lincoln Evening News & Daily Call, 9/19/1898",1898.09.19.a.R.Sully.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1898.09.19.a.R,1898.09.19.a.R,716.0
5612,1897.03.15.b.R,Reported 15-Mar-1897,1897.0,Unprovoked,NaN,Mediterranean Sea,NaN,Swimming,male,M,...,Y,NaN,NaN,"Daily Northwestern, 5/15/1897",1897.03.15.b.R-Mediterranean.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1897.03.15.b.R,1897.03.15.b.R,691.0
5636,1895.06.13.R,Reported 13-Jun-1895,1895.0,Unprovoked,NaN,NaN,NaN,Diving,Marsh,M,...,N,NaN,NaN,"Lima Times, 6/13/1895",1895.06.13.R-EnglishDiver.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1895.06.13.R,1895.06.13.R,667.0
5742,1887.07.30,30-Jul-1887,1887.0,Sea Disaster,NaN,Gulf of California,NaN,"Sea disaster, wreck of the sloop Sara",2 males,M,...,Y,NaN,NaN,"Austin Weekly Statesman, 8/11/1887",1887.07.30-TheSara.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1887.07.30,1887.07.30,561.0
5770,1885.04.16.R,Reported 16-Apr-1885,1885.0,Unprovoked,NaN,NaN,NaN,Swimming,2 males,M,...,Y,NaN,NaN,"Gleaner (Jamaica), 4/16/1885",1885.04.16.R-GermanShip.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1885.04.16.R,1885.04.16.R,533.0
5808,1881.08.16.R,Reported 16-Aug-1881,1881.0,Unprovoked,NaN,Western Banks,NaN,"Floating, holding onto an oar after dory capsized",George Sedgwick,M,...,Y,NaN,NaN,"Lewiston Evening Journal, 8/16/1881",1881.08.16.R-Sedgwick.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1881.08.16.R,1881.08.16.R,495.0
5810,1881.06.25,25-Jul-1881,1881.0,Unprovoked,NaN,NaN,Santa Cruz,Bathing,Father Hudson,M,...,N,NaN,NaN,"Grey River Argus,10/3/1881, p.2",1881.06.25-FatherHudson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1881.06.25,1881.06.25,493.0
5839,1878.10.13,13-Oct-1878,1878.0,Unprovoked,NaN,NaN,NaN,Jumped overboard after murdering 2 shipmates,Sherrington,M,...,Y,NaN,NaN,The Maitland Mercury & Hunter River General Ad...,1878.10.13-Sherrington.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1878.10.13,1878.10.13,464.0
5885,1874.06.15.a.R,Reported 15-Jun-1874,1874.0,Unprovoked,NaN,NaN,NaN,Salvaging a shipwreck,male,M,...,N,NaN,NaN,"Daily Southern Cross, 6/15/1874",1874.06.15.a.R-Achilles-tendon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1874.06.15.a.R,1874.06.15.a.R,418.0
5920,1869.04.10,10-Apr-1869,1869.0,Invalid,NaN,NaN,NaN,Fell overboard,Christian Frederick,M,...,NaN,NaN,Shark involvement prior to death unconfirmed,"Nelson Examiner & New Zealand Chronicle, 4/24/...",1869.04.10-Frederick.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1869.04.10,1869.04.10,383.0
5996,1856.11.20.R,Reported 20-Nov-1856,1856.0,Unprovoked,NaN,NaN,NaN,Swimming,Cornelius Conhlren,M,...,Y,NaN,NaN,"Pacific Commercial Advertiser, 11/20/1856",1856.11.20.R-Conhlren.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1856.11.20.R,1856.11.20.R,307.0
6001,1855.07.28,28-Jul-1855,1855.0,Unprovoked,NaN,NaN,NaN,Bathing,"a young boy, one of the crew of the Post Boy",M,...,Y,NaN,NaN,"Maitland Mercury, 8/25/1855",1855.07.28-PostBoy-sailors.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1855.07.28,1855.07.28,302.0
6092,1830.04.22.R,Reported 22-Apr-1830,1830.0,Unprovoked,NaN,NaN,NaN,NaN,Jose,M,...,Y,Night,NaN,"The Torchlight & Public Advertiser, 4/22/1830",1830.04.22.R-Jose.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1830.04.22.R,1830.04.22.R,211.0
6119,1811.03.01,01-Mar-1811,1811.0,Unprovoked,NaN,NaN,NaN,Fell overboard,John Walker,M,...,Y,NaN,NaN,Journal of Captain Marryat,1811.03.01-John-Walker.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1811.03.01,1811.03.01,184.0
6131,1801.12.18.R,Reported 18-Dec-1801,1801.0,Provoked,NaN,NaN,NaN,Standing on landed shark's tail,Stephen Pettigew,N,...,Y,NaN,12' shark,"The Evening Post, 12/18/1801",1801.12.18.R-Pettigrew.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1801.12.18.R,1801.12.18.R,172.0
6133,1797.05.28.R,Reported May-28-1797,1797.0,Unprovoked,NaN,NaN,NaN,Dropped overboard,child,NaN,...,Y,NaN,NaN,The Observer 5/28/1797,1797.05.28.R-Cloverdale.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1797.05.28.R,1797.05.28.R,170.0
6137,1787.07.05,05-Jul-1787,1787.0,Unprovoked,NaN,St Helena,Landing Place,Swimming,Private Isaac Hicksled,M,...,Y,NaN,NaN,"H.R. Janisch (1885), Extracts from the St. Hel...",1787.07.05-Hicksled.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1787.07.05,1787.07.05,166.0
6155,1742.12.17,17-Dec-1742,1742.0,Unprovoked,NaN,NaN,Carlisle Bay,Swimming,2 impressed seamen,M,...,Y,NaN,NaN,"C. Moore, GSAF",1742.12.17-AdviceSeamen.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1742.12.17,1742.12.17,148.0
6165,1638.00.00.R,Reported 1638,1638.0,Unprovoked,NaN,NaN,NaN,NaN,sailors,M,...,UNKNOWN,NaN,NaN,Sir Thomas Herbert,1638.00.00.R-Herbert,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1638.00.00.R,1638.00.00.R,138.0
6171,1555.00.00,1555,1555.0,Unprovoked,NaN,NaN,NaN,Swimming,male,M,...,UNKNOWN,NaN,NaN,Olaus Magnus,1555.00.00 - Olaus Magnus.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1555.00.00,1555.00.00,132.0
6175,0077.00.00,77 A.D.,77.0,Unprovoked,NaN,Ionian Sea,NaN,Sponge diving,males,M,...,Y,NaN,NaN,Perils mentioned by Pliny the Elder (23 A.D. t...,77AD-Pliny.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,0077.00.00,0077.00.00,128.0
6177,0000.0214,Ca. 214 B.C.,0.0,Unprovoked,NaN,Ionian Sea,NaN,Ascending from a dive,"Tharsys, a sponge diver",M,...,Y,NaN,NaN,"Reported by Greek poet, Leonidas of Tarentum (...",214BC-Tharsys.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,0000.0214,0000.0214,126.0
6199,ND-0124,Before 2011,0.0,Provoked,NaN,NaN,NaN,NaN,Phillip Peters,M,...,N,NaN,NaN,"Watertown Daily Times, 7/8/2011",ND-0124-Peters.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND-0124,ND-0124,104.0
6206,ND-0114,Before 2012,0.0,Unprovoked,NaN,NaN,In a river feeding into the Bay of Bengal,Netting shrimp,Sametra Mestri,F,...,N,NaN,NaN,National Georgraphic Television,ND-0114-BayOfBengal.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND-0114,ND-0114,97.0
6259,ND.0044,1941-1945,0.0,Sea Disaster,NaN,NaN,NaN,A group of survivors on a raft for 17-days,C.,NaN,...,Y,Late afternoon,1.2 m [4'] shark,"G.A. Llano in Airmen Against the Sea, p.69",ND-0044-C.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0044,ND.0044,44.0

In [38]:
#Queremos corregir country, area y location pero vemos que si las 3 son nulas no es posible asignar ubicacion, asi que las borramos

df.dropna(subset=['country', 'area', 'location'], how='all')

,case number,date,year,type,country,area,location,activity,name,sex,...,fatal (y/n),time,species,investigator or source,pdf,href formula,href,case number.1,case number.2,original order
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,...,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,...,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,...,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,...,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,...,Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0

In [39]:
nan_cols = df.isna().sum() # suma de elemento nulos  

nan_cols

case number                  0
date                         0
year                         0
type                         0
country                     50
area                       455
location                   540
activity                   544
name                       210
sex                        565
age                       2831
injury                      28
fatal (y/n)                539
time                      3354
species                   2838
investigator or source      17
pdf                          0
href formula                 1
href                         0
case number.1                0
case number.2                0
original order               0
dtype: int64

In [40]:
df[df['country'].isna()] #buscamos el nulo en country y me doy cuenta de que me han hecho la 13/14, hay valores que pone NaN en el data frame que son cadenas de texto y no nulos... lo dejo para mas adelante y me centro en los nulos

,case number,date,year,type,country,area,location,activity,name,sex,...,fatal (y/n),time,species,investigator or source,pdf,href formula,href,case number.1,case number.2,original order
62,2017.11.13.R,Reported 13-Nov-2017,2017.0,Unprovoked,NaN,NaN,NaN,Surfing,Timur Yunusov,M,...,N,NaN,NaN,Instagram,2017.11.13.R-Timur.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.11.13.R,2017.11.13.R,6241.0
525,2014.08.00,Aug-2014,2014.0,Invalid,NaN,NaN,NaN,Sea disaster,Cuban refugees,M,...,NaN,NaN,Shark involvement not confirmed,"Associated Press, 11/27/2014",2014.08.00-Cuban-refugees.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2014.08.00,2014.08.00,5778.0
2956,1983.00.00.d,Ca. 1983,1983.0,Unprovoked,NaN,English Channel,NaN,Swimming,Padma Shri Taranath Narayan Shenoy,M,...,N,NaN,NaN,"Times of India, 2/5/2012",1983.00.00.d-Shenoy.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1983.00.00.d,1983.00.00.d,3347.0
3378,1970.11.00,Nov-1970,1970.0,Unprovoked,NaN,NaN,NaN,NaN,Heinz Plotsky,M,...,N,NaN,NaN,"H.D. Baldridge (1994), SAF Case #1645",1970.11.00-NV-Plotsky.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1970.11.00,1970.11.00,2925.0
3387,1970.08.02,02-Aug-1970,1970.0,Invalid,NaN,Caribbean Sea,Between St. Kitts & Nevis,Sea Disaster Sinking of ferryboat Christina,NaN,NaN,...,NaN,Afternoon,Shark involvement prior to death was not confi...,"Rome News Tribune, 8/3/1970",1970.08.02-Christina-ferryboat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1970.08.02,1970.08.02,2916.0
3388,1970.07.05,5-Jul-1970,1970.0,Unprovoked,NaN,NaN,NaN,NaN,male,M,...,N,Night,Mako shark,"H.D. Baldridge (1994), SAF Case #1628",1970.07.05-NV-male.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1970.07.05,1970.07.05,2915.0
3395,1970.04.00.b,Apr-1970,1970.0,Provoked,NaN,NaN,NaN,Freediving,Lionel Jarvis,M,...,N,NaN,Wobbegong shark,"H.D. Baldridge (1994), SAF Case #1616",1970.04.00.b-NV-Jarvis.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1970.04.00.b,1970.04.00.b,2908.0
3399,1970.02.05,5-Feb-1970,1970.0,Unprovoked,NaN,NaN,NaN,Wading,Sally Anne Irvine,F,...,N,NaN,Carpet shark,H.D. Baldridge (1994) SAF Case #1626,1970.02.05-NV-Irvine.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1970.02.05,1970.02.05,2904.0
3425,1969.08.00,Aug-1969,1969.0,Unprovoked,NaN,NaN,NaN,NaN,Rodney Hughes,M,...,N,NaN,NaN,H.D. Baldridge (1994) SAF Case #1602,1969.08.00-NV-Hughes.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1969.08.00,1969.08.00,2878.0
3605,1965.10.21,21-Oct-1965,1965.0,Unprovoked,NaN,NaN,Florida Strait,The boat Caribou II sank,Mario Castellanos,M,...,N,NaN,NaN,"Lodi News Sentinel, 10/30/1965",1965.10.21-Castellanos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1965.10.21,1965.10.21,2698.0
3661,1964.09.27,27-Sep-1964,1964.0,Invalid,NaN,NaN,NaN,Spearfishing,Giancarlo Griffon,M,...,NaN,11h00,Shark involvement prior to death was not confi...,C. Moore. GSAF,1964.09.27-Griffon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1964.09.27,1964.09.27,2642.0
4018,1960.01.26,26-Jan-1960,1960.0,Sea Disaster,NaN,"Between Timor & Darwin, Australia",NaN,Portuguese Airliner with 9 people aboard went ...,NaN,NaN,...,N,NaN,NaN,"V.M. Coppleson (1962), p.260",1960.01.26-Portuguese airliner.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1960.01.26,1960.01.26,2285.0
4231,1956.09.13,13-Sep-1956,1956.0,Unprovoked,NaN,Near the Andaman & Nicobar Islands,NaN,Climbing back on ship,male,M,...,Y,P.M.,Blue shark,M. Hosina,1956.09.13-TunaBoat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1956.09.13,1956.09.13,2072.0
4266,1956.00.00.g,1956,1956.0,Sea Disaster,NaN,Between Comores & Madagascar,Geyser Bank,Shipwreck,"Captain Eric Hunt, the cook & a French passenger",M,...,Y,NaN,NaN,dinofish.com,1956.00.00.g-Capt-Hunt.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1956.00.00.g,1956.00.00.g,2037.0
4498,1949.12.00.b,Dec-1949,1949.0,Sea Disaster,NaN,Caribbean Sea,Between Cuba & Costa Rica,"Sea Disaster, sinking of the motorship Wingate","Albert Battles, James Dean & 4 crew",M,...,Y,NaN,Shark involvement not confirmed,"Canberra Times, 1/6/1950",1949.12.00.b-Wingate.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1949.12.00.b,1949.12.00.b,1805.0
4639,1944.10.24,24-Oct-1944,1944.0,Sea Disaster,NaN,NaN,225 miles east of Hong Kong,Japanese POW ship Arisan Maru with 1800 Americ...,NaN,M,...,Y,>17h30,NaN,internet (multiple),1944.10.24-ArisanMaru.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1944.10.24,1944.10.24,1664.0
4700,1942.11.00.a,Nov-1942,1942.0,Sea Disaster,NaN,Off South American coast,NaN,Dutch merchant ship Zaandam torpedoed by the ...,NaN,M,...,Y,NaN,NaN,"M. Murphy; V.M. Coppleson (1962), pp.207-208",1942.11.00.a-Izzi.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1942.11.00.a,1942.11.00.a,1603.0
4712,1942.06.00,Jun-1942,1942.0,Unprovoked,NaN,300 miles east of St. Thomas (Virgin Islands),NaN,On life raft tethered to lifeboat. A seaman pu...,male,M,...,N,NaN,NaN,"V.M. Coppleson (1962), p.258",1942.06.00-on-life-raft.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1942.06.00,1942.06.00,1591.0
4726,1942.00.00.e,1942,1942.0,Sea Disaster,NaN,NaN,NaN,Jumped overboard from torpedoed Panamanian fre...,male,M,...,Y,NaN,NaN,"V.M. Coppleson (1962), p.258",1942.00.00.e-seaman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1942.00.00.e,1942.00.00.e,1577.0
4729,1942.00.00.b,1942,1942.0,Boating,NaN,NaN,NaN,"Days before the surrender of Singapore, the 3 ...","Bombardier J. Hall, Private Green of the Sherw...",M,...,N,NaN,NaN,"V.M. Coppleson (1962), p.206",1942.00.00.b-Hall-Green-Jennings.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1942.00.00.b,1942.00.00.b,1574.0
4911,1935.04.12.R,Reported 12-Apr-1935,1935.0,Unprovoked,NaN,NaN,NaN,Diving,Pearl Purdy Scott,F,...,N,NaN,NaN,"Port Arthur News, 4/12/1935",1935.04.12.R-PearlPurdyScott.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1935.04.12.R,1935.04.12.R,1392.0
5020,1931.04.27.R,Reported 27-Apr-1931,1931.0,Unprovoked,NaN,French Southern Territories,Île Saint-Paul,"Fishing, boat capsized",Quillezic,M,...,Y,NaN,NaN,"Los Angeles Times, 4/27/1931",1931.04.27.R-Quillezic.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1931.04.27.R,1931.04.27.R,1283.0
5060,1929.12.09.R,Reported 09-Dec-1929,1929.0,Unprovoked,NaN,NaN,NaN,NaN,Thomas Duggan,M,...,Y,NaN,NaN,"The Age, 12/9/1929",1929.12.09.R-Duggan.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1929.12.09.R,1929.12.09.R,1243.0
5425,1909.01.17,17-Jan-1909,1909.0,Invalid,NaN,NaN,Near the equator,Jumped overboard,Thomas Butler,M,...,NaN,NaN,Questionable,"Star, 3/18/1909",1909.01.17-Butler.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1909.01.17,1909.01.17,878.0
5586,1898.09.19.b.R,Reported 19-Sep-1898,1898.0,Unprovoked,NaN,NaN,NaN,Diving,Halletts,M,...,N,NaN,NaN,"Lincoln Evening News & Daily Call, 9/19/1898",1898.09.19.b.R-Halletts.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1898.09.19.b.R,1898.09.19.b.R,717.0
5587,1898.09.19.a.R,Reported 19-Sep-1898,1898.0,Unprovoked,NaN,NaN,NaN,Diving,male,M,...,N,NaN,NaN,"Lincoln Evening News & Daily Call, 9/19/1898",1898.09.19.a.R.Sully.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1898.09.19.a.R,1898.09.19.a.R,716.0
5612,1897.03.15.b.R,Reported 15-Mar-1897,1897.0,Unprovoked,NaN,Mediterranean Sea,NaN,Swimming,male,M,...,Y,NaN,NaN,"Daily Northwestern, 5/15/1897",1897.03.15.b.R-Mediterranean.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1897.03.15.b.R,1897.03.15.b.R,691.0
5636,1895.06.13.R,Reported 13-Jun-1895,1895.0,Unprovoked,NaN,NaN,NaN,Diving,Marsh,M,...,N,NaN,NaN,"Lima Times, 6/13/1895",1895.06.13.R-EnglishDiver.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1895.06.13.R,1895.06.13.R,667.0
5742,1887.07.30,30-Jul-1887,1887.0,Sea Disaster,NaN,Gulf of California,NaN,"Sea disaster, wreck of the sloop Sara",2 males,M,...,Y,NaN,NaN,"Austin Weekly Statesman, 8/11/1887",1887.07.30-TheSara.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1887.07.30,1887.07.30,561.0
5770,1885.04.16.R,Reported 16-Apr-1885,1885.0,Unprovoked,NaN,NaN,NaN,Swimming,2 males,M,...,Y,NaN,NaN,"Gleaner (Jamaica), 4/16/1885",1885.04.16.R-GermanShip.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1885.04.16.R,1885.04.16.R,533.0
5808,1881.08.16.R,Reported 16-Aug-1881,1881.0,Unprovoked,NaN,Western Banks,NaN,"Floating, holding onto an oar after dory capsized",George Sedgwick,M,...,Y,NaN,NaN,"Lewiston Evening Journal, 8/16/1881",1881.08.16.R-Sedgwick.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1881.08.16.R,1881.08.16.R,495.0
5810,1881.06.25,25-Jul-1881,1881.0,Unprovoked,NaN,NaN,Santa Cruz,Bathing,Father Hudson,M,...,N,NaN,NaN,"Grey River Argus,10/3/1881, p.2",1881.06.25-FatherHudson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1881.06.25,1881.06.25,493.0
5839,1878.10.13,13-Oct-1878,1878.0,Unprovoked,NaN,NaN,NaN,Jumped overboard after murdering 2 shipmates,Sherrington,M,...,Y,NaN,NaN,The Maitland Mercury & Hunter River General Ad...,1878.10.13-Sherrington.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1878.10.13,1878.10.13,464.0
5885,1874.06.15.a.R,Reported 15-Jun-1874,1874.0,Unprovoked,NaN,NaN,NaN,Salvaging a shipwreck,male,M,...,N,NaN,NaN,"Daily Southern Cross, 6/15/1874",1874.06.15.a.R-Achilles-tendon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1874.06.15.a.R,1874.06.15.a.R,418.0
5920,1869.04.10,10-Apr-1869,1869.0,Invalid,NaN,NaN,NaN,Fell overboard,Christian Frederick,M,...,NaN,NaN,Shark involvement prior to death unconfirmed,"Nelson Examiner & New Zealand Chronicle, 4/24/...",1869.04.10-Frederick.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1869.04.10,1869.04.10,383.0
5996,1856.11.20.R,Reported 20-Nov-1856,1856.0,Unprovoked,NaN,NaN,NaN,Swimming,Cornelius Conhlren,M,...,Y,NaN,NaN,"Pacific Commercial Advertiser, 11/20/1856",1856.11.20.R-Conhlren.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1856.11.20.R,1856.11.20.R,307.0
6001,1855.07.28,28-Jul-1855,1855.0,Unprovoked,NaN,NaN,NaN,Bathing,"a young boy, one of the crew of the Post Boy",M,...,Y,NaN,NaN,"Maitland Mercury, 8/25/1855",1855.07.28-PostBoy-sailors.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1855.07.28,1855.07.28,302.0
6092,1830.04.22.R,Reported 22-Apr-1830,1830.0,Unprovoked,NaN,NaN,NaN,NaN,Jose,M,...,Y,Night,NaN,"The Torchlight & Public Advertiser, 4/22/1830",1830.04.22.R-Jose.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1830.04.22.R,1830.04.22.R,211.0
6119,1811.03.01,01-Mar-1811,1811.0,Unprovoked,NaN,NaN,NaN,Fell overboard,John Walker,M,...,Y,NaN,NaN,Journal of Captain Marryat,1811.03.01-John-Walker.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1811.03.01,1811.03.01,184.0
6131,1801.12.18.R,Reported 18-Dec-1801,1801.0,Provoked,NaN,NaN,NaN,Standing on landed shark's tail,Stephen Pettigew,N,...,Y,NaN,12' shark,"The Evening Post, 12/18/1801",1801.12.18.R-Pettigrew.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1801.12.18.R,1801.12.18.R,172.0
6133,1797.05.28.R,Reported May-28-1797,1797.0,Unprovoked,NaN,NaN,NaN,Dropped overboard,child,NaN,...,Y,NaN,NaN,The Observer 5/28/1797,1797.05.28.R-Cloverdale.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1797.05.28.R,1797.05.28.R,170.0
6137,1787.07.05,05-Jul-1787,1787.0,Unprovoked,NaN,St Helena,Landing Place,Swimming,Private Isaac Hicksled,M,...,Y,NaN,NaN,"H.R. Janisch (1885), Extracts from the St. Hel...",1787.07.05-Hicksled.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1787.07.05,1787.07.05,166.0
6155,1742.12.17,17-Dec-1742,1742.0,Unprovoked,NaN,NaN,Carlisle Bay,Swimming,2 impressed seamen,M,...,Y,NaN,NaN,"C. Moore, GSAF",1742.12.17-AdviceSeamen.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1742.12.17,1742.12.17,148.0
6165,1638.00.00.R,Reported 1638,1638.0,Unprovoked,NaN,NaN,NaN,NaN,sailors,M,...,UNKNOWN,NaN,NaN,Sir Thomas Herbert,1638.00.00.R-Herbert,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1638.00.00.R,1638.00.00.R,138.0
6171,1555.00.00,1555,1555.0,Unprovoked,NaN,NaN,NaN,Swimming,male,M,...,UNKNOWN,NaN,NaN,Olaus Magnus,1555.00.00 - Olaus Magnus.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1555.00.00,1555.00.00,132.0
6175,0077.00.00,77 A.D.,77.0,Unprovoked,NaN,Ionian Sea,NaN,Sponge diving,males,M,...,Y,NaN,NaN,Perils mentioned by Pliny the Elder (23 A.D. t...,77AD-Pliny.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,0077.00.00,0077.00.00,128.0
6177,0000.0214,Ca. 214 B.C.,0.0,Unprovoked,NaN,Ionian Sea,NaN,Ascending from a dive,"Tharsys, a sponge diver",M,...,Y,NaN,NaN,"Reported by Greek poet, Leonidas of Tarentum (...",214BC-Tharsys.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,0000.0214,0000.0214,126.0
6199,ND-0124,Before 2011,0.0,Provoked,NaN,NaN,NaN,NaN,Phillip Peters,M,...,N,NaN,NaN,"Watertown Daily Times, 7/8/2011",ND-0124-Peters.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND-0124,ND-0124,104.0
6206,ND-0114,Before 2012,0.0,Unprovoked,NaN,NaN,In a river feeding into the Bay of Bengal,Netting shrimp,Sametra Mestri,F,...,N,NaN,NaN,National Georgraphic Television,ND-0114-BayOfBengal.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND-0114,ND-0114,97.0
6259,ND.0044,1941-1945,0.0,Sea Disaster,NaN,NaN,NaN,A group of survivors on a raft for 17-days,C.,NaN,...,Y,Late afternoon,1.2 m [4'] shark,"G.A. Llano in Airmen Against the Sea, p.69",ND-0044-C.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0044,ND.0044,44.0

In [41]:
filas_con_nulos = df[df['country'].isna()].index.to_list() # con esto saco las filas de nulos de country
filas_con_nulos

[62,
 525,
 2956,
 3378,
 3387,
 3388,
 3395,
 3399,
 3425,
 3605,
 3661,
 4018,
 4231,
 4266,
 4498,
 4639,
 4700,
 4712,
 4726,
 4729,
 4911,
 5020,
 5060,
 5425,
 5586,
 5587,
 5612,
 5636,
 5742,
 5770,
 5808,
 5810,
 5839,
 5885,
 5920,
 5996,
 6001,
 6092,
 6119,
 6131,
 6133,
 6137,
 6155,
 6165,
 6171,
 6175,
 6177,
 6199,
 6206,
 6259]

In [42]:
df.drop([62, 525, 2956, 3378, 3387, 3388, 3395, 3399, 3425, 3605, 3661, 4018, 4231, 4266, 4498, 4639, 4700, 4712, 4726, 4729, 4911, 5020, 5060, 5425, 5586, 5587, 5612, 5636, 5742, 5770, 5808, 5810, 5839, 5885, 5920, 5996, 6001, 6092, 6119, 6131, 6133, 6137, 6155, 6165, 6171, 6175, 6177, 6199, 6206, 6259], inplace=True)

In [43]:
nan_cols = df.isna().sum() # suma de elemento nulos  

nan_cols

case number                  0
date                         0
year                         0
type                         0
country                      0
area                       420
location                   501
activity                   537
name                       206
sex                        561
age                       2790
injury                      26
fatal (y/n)                534
time                      3311
species                   2800
investigator or source      17
pdf                          0
href formula                 1
href                         0
case number.1                0
case number.2                0
original order               0
dtype: int64

In [44]:
df[df['area'].isna()] #buscamos el nulo en area

,case number,date,year,type,country,area,location,activity,name,sex,...,fatal (y/n),time,species,investigator or source,pdf,href formula,href,case number.1,case number.2,original order
32,2018.04.09,09-Apr-2018,2018.0,Unprovoked,NEW CALEDONIA,NaN,"Magenta Beach, Noumea",Windsurfing,NaN,NaN,...,N,17h00,2 m shark,"Les Nouvelles Caledoniennes, 4/10/2018",2018.04.09-Magenta.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.09,2018.04.09,6271.0
33,2018.04.05,05-Apr-2018,2018.0,Unprovoked,BAHAMAS,NaN,Bimini,Swimming,Shane McConnell,M,...,N,18h00,Bull shark,"K. McMurray, TrackingSharks.com",2018.04.05-McConnell.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.05,2018.04.05,6270.0
48,2018.01.21,21-Jan-2018,2018.0,Unprovoked,NEW CALEDONIA,NaN,Nouville,Spearfishing,male,M,...,N,15h30,"Bull shark, 3 m",TrackingSharks.com,2018.01.21-NewCaledonia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.01.21,2018.01.21,6255.0
56,2017.12.09,09-Dec-2017,2017.0,Unprovoked,BAHAMAS,NaN,NaN,Snorkeling,Sarah Illig-Carroll,F,...,N,NaN,Nurse shark. 5',"Daily Star, 12/11/2017",2017.12.09-Carroll.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.12.09,2017.12.09,6247.0
59,2017.11.25.R,Reported 25-Nov-2017,2017.0,Sea Disaster,LIBYA,NaN,Gars Garabulli,2 boats capsized,31 migrants,NaN,...,Y,NaN,Some drowned but other may have been killed by...,"TG Com 24, 11/25/2017",2017.11.25.R-Libya.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.11.25.R,2017.11.25.R,6244.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6291,ND.0011,Before 1911,0.0,Unprovoked,ASIA?,NaN,NaN,Swimming,Mr. Masury,M,...,N,NaN,NaN,"Ref. J. T. Dubois in N.Y. Sun, 3/19/1911",ND-0011-Masury.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0011,ND.0011,12.0
6293,ND.0009,Before 1906,0.0,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,boy,M,...,Y,NaN,Blue pointer,"NY Sun, 9/9/1906, referring to account by Loui...",ND-0009-boy-Australia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0009,ND.0009,10.0
6294,ND.0008,Before 1906,0.0,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,fisherman,M,...,Y,NaN,Blue pointer,"NY Sun, 9/9/1906, referring to account by Loui...",ND-0008-Fisherman2-Australia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0008,ND.0008,9.0
6295,ND.0007,Before 1906,0.0,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,fisherman,M,...,Y,NaN,Blue pointers,"NY Sun, 9/9/1906, referring to account by Loui...",ND-0007 - Fisherman-Australia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0007,ND.0007,8.0
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,...,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0

In [45]:
filas_con_nulos = df[df['area'].isna()].index.to_list() # con esto saco las filas de nulos de area
filas_con_nulos

[32,
 33,
 48,
 56,
 59,
 90,
 101,
 129,
 132,
 206,
 226,
 229,
 248,
 270,
 296,
 325,
 327,
 370,
 388,
 410,
 425,
 440,
 446,
 465,
 469,
 517,
 538,
 543,
 565,
 578,
 581,
 589,
 602,
 629,
 631,
 642,
 655,
 674,
 685,
 691,
 692,
 771,
 794,
 822,
 856,
 891,
 938,
 966,
 969,
 975,
 1002,
 1088,
 1089,
 1093,
 1111,
 1119,
 1161,
 1162,
 1192,
 1195,
 1224,
 1234,
 1262,
 1275,
 1365,
 1366,
 1401,
 1434,
 1443,
 1448,
 1528,
 1554,
 1567,
 1569,
 1589,
 1603,
 1697,
 1848,
 1880,
 1928,
 1947,
 1973,
 2014,
 2017,
 2027,
 2044,
 2053,
 2076,
 2132,
 2138,
 2196,
 2265,
 2269,
 2305,
 2331,
 2389,
 2398,
 2401,
 2441,
 2444,
 2445,
 2459,
 2511,
 2569,
 2581,
 2594,
 2632,
 2674,
 2721,
 2722,
 2723,
 2726,
 2727,
 2733,
 2776,
 2799,
 2819,
 2868,
 2887,
 2897,
 2937,
 2970,
 2986,
 3024,
 3033,
 3056,
 3071,
 3079,
 3085,
 3090,
 3157,
 3169,
 3245,
 3246,
 3267,
 3301,
 3338,
 3366,
 3367,
 3396,
 3426,
 3434,
 3454,
 3471,
 3487,
 3494,
 3496,
 3499,
 3504,
 3516,
 3527,
 3543,
 3545,
 3562,
 3572,
 3579,
 3581,
 3591,
 3599,
 3613,
 3622,
 3625,
 3626,
 3646,
 3692,
 3693,
 3704,
 3736,
 3737,
 3746,
 3764,
 3773,
 3775,
 3783,
 3806,
 3877,
 3884,
 3891,
 3921,
 3938,
 3960,
 4008,
 4026,
 4065,
 4122,
 4140,
 4198,
 4229,
 4252,
 4254,
 4263,
 4297,
 4326,
 4332,
 4337,
 4338,
 4341,
 4352,
 4384,
 4388,
 4391,
 4396,
 4412,
 4430,
 4441,
 4444,
 4493,
 4497,
 4511,
 4540,
 4561,
 4581,
 4598,
 4615,
 4616,
 4627,
 4635,
 4638,
 4642,
 4645,
 4647,
 4654,
 4659,
 4670,
 4673,
 4674,
 4675,
 4677,
 4680,
 4681,
 4685,
 4686,
 4693,
 4694,
 4695,
 4696,
 4697,
 4703,
 4705,
 4706,
 4707,
 4709,
 4710,
 4728,
 4731,
 4737,
 4745,
 4750,
 4757,
 4788,
 4793,
 4802,
 4812,
 4826,
 4833,
 4843,
 4847,
 4867,
 4902,
 4934,
 4955,
 4976,
 5002,
 5022,
 5029,
 5036,
 5044,
 5053,
 5054,
 5087,
 5094,
 5096,
 5101,
 5104,
 5107,
 5124,
 5143,
 5144,
 5158,
 5232,
 5245,
 5275,
 5291,
 5296,
 5307,
 5313,
 5323,
 5324,
 5349,
 5358,
 5366,
 5400,
 5480,
 5493,
 5513,
 5514,
 5519,
 5525,
 5575,
 5588,
 5596,
 5597,
 5614,
 5621,
 5635,
 5666,
 5667,
 5669,
 5673,
 5675,
 5683,
 5688,
 5693,
 5697,
 5701,
 5702,
 5703,
 5705,
 5727,
 5739,
 5740,
 5766,
 5777,
 5785,
 5789,
 5796,
 5798,
 5800,
 5802,
 5812,
 5816,
 5825,
 5846,
 5848,
 5850,
 5854,
 5880,
 5886,
 5888,
 5894,
 5895,
 5897,
 5906,
 5923,
 5927,
 5942,
 5945,
 5946,
 5959,
 5960,
 5961,
 5966,
 5975,
 5976,
 5990,
 5995,
 6019,
 6031,
 6044,
 6049,
 6053,
 6056,
 6057,
 6058,
 6060,
 6069,
 6080,
 6095,
 6100,
 6103,
 6105,
 6108,
 6110,
 6111,
 6115,
 6117,
 6121,
 6122,
 6123,
 6125,
 6130,
 6134,
 6138,
 6140,
 6141,
 6144,
 6145,
 6146,
 6148,
 6149,
 6150,
 6158,
 6161,
 6163,
 6164,
 6170,
 6174,
 6181,
 6192,
 6193,
 6195,
 6196,
 6204,
 6207,
 6215,
 6228,
 6234,
 6237,
 6238,
 6257,
 6269,
 6270,
 6273,
 6276,
 6280,
 6291,
 6293,
 6294,
 6295,
 6300]

In [46]:
df.drop([32, 33, 48, 56, 59, 90, 101, 129, 132, 206, 226, 229, 248, 270, 296, 325, 327, 370, 388, 410, 425, 440, 446, 465, 469, 517, 538, 543, 565, 578, 581, 589, 602, 629, 631, 642, 655, 674, 685, 691, 692, 771, 794, 822, 856, 891, 938, 966, 969, 975, 1002, 1088, 1089, 1093, 1111, 1119, 1161, 1162, 1192, 1195, 1224, 1234, 1262, 1275, 1365, 1366, 1401, 1434, 1443, 1448, 1528, 1554, 1567, 1569, 1589, 1603, 1697, 1848, 1880, 1928, 1947, 1973, 2014, 2017, 2027, 2044, 2053, 2076, 2132, 2138, 2196, 2265, 2269, 2305, 2331, 2389, 2398, 2401, 2441, 2444, 2445, 2459, 2511, 2569, 2581, 2594, 2632, 2674, 2721, 2722, 2723, 2726, 2727, 2733, 2776, 2799, 2819, 2868, 2887, 2897, 2937, 2970, 2986, 3024, 3033, 3056, 3071, 3079, 3085, 3090, 3157, 3169, 3245, 3246, 3267, 3301, 3338, 3366, 3367, 3396, 3426, 3434, 3454, 3471, 3487, 3494, 3496, 3499, 3504, 3516, 3527, 3543, 3545, 3562, 3572, 3579, 3581, 3591, 3599, 3613, 3622, 3625, 3626, 3646, 3692, 3693, 3704, 3736, 3737, 3746, 3764, 3773, 3775, 3783, 3806, 3877, 3884, 3891, 3921, 3938, 3960, 4008, 4026, 4065, 4122, 4140, 4198, 4229, 4252, 4254, 4263, 4297, 4326, 4332, 4337, 4338, 4341, 4352, 4384, 4388, 4391, 4396, 4412, 4430, 4441, 4444, 4493, 4497, 4511, 4540, 4561, 4581, 4598, 4615, 4616, 4627, 4635, 4638, 4642, 4645, 4647, 4654, 4659, 4670, 4673, 4674, 4675, 4677, 4680, 4681, 4685, 4686, 4693, 4694, 4695, 4696, 4697, 4703, 4705, 4706, 4707, 4709, 4710, 4728, 4731, 4737, 4745, 4750, 4757, 4788, 4793, 4802, 4812, 4826, 4833, 4843, 4847, 4867, 4902, 4934, 4955, 4976, 5002, 5022, 5029, 5036, 5044, 5053, 5054, 5087, 5094, 5096, 5101, 5104, 5107, 5124, 5143, 5144, 5158, 5232, 5245, 5275, 5291, 5296, 5307, 5313, 5323, 5324, 5349, 5358, 5366, 5400, 5480, 5493, 5513, 5514, 5519, 5525, 5575, 5588, 5596, 5597, 5614, 5621, 5635, 5666, 5667, 5669, 5673, 5675, 5683, 5688, 5693, 5697, 5701, 5702, 5703, 5705, 5727, 5739, 5740, 5766, 5777, 5785, 5789, 5796, 5798, 5800, 5802, 5812, 5816, 5825, 5846, 5848, 5850, 5854, 5880, 5886, 5888, 5894, 5895, 5897, 5906, 5923, 5927, 5942, 5945, 5946, 5959, 5960, 5961, 5966, 5975, 5976, 5990, 5995, 6019, 6031, 6044, 6049, 6053, 6056, 6057, 6058, 6060, 6069, 6080, 6095, 6100, 6103, 6105, 6108, 6110, 6111, 6115, 6117, 6121, 6122, 6123, 6125, 6130, 6134, 6138, 6140, 6141, 6144, 6145, 6146, 6148, 6149, 6150, 6158, 6161, 6163, 6164, 6170, 6174, 6181, 6192, 6193, 6195, 6196, 6204, 6207, 6215, 6228, 6234, 6237, 6238, 6257, 6269, 6270, 6273, 6276, 6280, 6291, 6293, 6294, 6295, 6300], inplace=True)

In [47]:
nan_cols = df.isna().sum() # suma de elemento nulos  

nan_cols

case number                  0
date                         0
year                         0
type                         0
country                      0
area                         0
location                   290
activity                   465
name                       168
sex                        501
age                       2480
injury                      22
fatal (y/n)                487
time                      2958
species                   2532
investigator or source      15
pdf                          0
href formula                 1
href                         0
case number.1                0
case number.2                0
original order               0
dtype: int64

In [48]:
df.shape

(5832, 22)

In [49]:
df[df['location'].isna()] #buscamos el nulo en area

,case number,date,year,type,country,area,location,activity,name,sex,...,fatal (y/n),time,species,investigator or source,pdf,href formula,href,case number.1,case number.2,original order
110,2017.07.26.R,Reported 26-Jul-2017,2017.0,Unprovoked,BAHAMAS,40 miles off Grand Bahama Island,NaN,Spearfishing,Michael Massey,M,...,N,NaN,NaN,"RevistaJaraysedal.es, 7/26/2017",2017.07.26.R-Massey.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.07.26.R,2017.07.26.R,6193.0
151,2017.04.26,26-Apr-2017,2017.0,Invalid,USA,Florida,NaN,Photo shoot,Molly Cavelli,F,...,NaN,NaN,No shark invovlement - it ws a publicity stunt,"The Sun, 5/6/2017",2017.05.26-Cavelli.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.04.26,2017.04.26,6152.0
171,2017.03.09,Reported 09-Mar-2017,2017.0,Unprovoked,BAHAMAS,Great Exuma,NaN,Washing hands,George Keywood,M,...,N,NaN,Lemon shark,"Kent Live, 3/9/2017",2017.03.09-Keywood.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.03.09,2017.03.09,6132.0
174,2017.02.21,21-Feb-2017,2017.0,Unprovoked,REUNION,Saint-Andre,NaN,Body boarding,Alexandre Naussance,M,...,Y,09h30,NaN,"Surfline, 2/21/2017",2017.02.21-Naussance.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.02.21,2017.02.21,6129.0
180,2017.02.01.a,01-Feb-2017,2017.0,Unprovoked,BAHAMAS,Bimini,NaN,Scuba Diving,Freek Vonk,M,...,N,NaN,Caribbean reef shark,"Dutch News, 2/2/2017",2017.02.01.a-Vonk.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.02.01.a,2017.02.01.a,6123.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6244,ND.0062,Before 1960,0.0,Unprovoked,BAHAMAS,Andros Islands,NaN,NaN,"male, a sponge Diver",M,...,N,NaN,"White shark, 7' to 8'","Star-Ledger (Newark, NJ), 8/22/1960",ND-0062-Spongediver-Andros.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0062,ND.0062,59.0
6255,ND.0049,Before 1956,0.0,Unprovoked,MARSHALL ISLANDS,Bikini Atoll,NaN,Swimming,male,M,...,N,NaN,NaN,J.E. Lasch,ND-0049-BikiniAtoll.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0049,ND.0049,48.0
6274,ND.0028,A few years before 1938,0.0,Boat,ITALY,Adriatic Sea,NaN,Wooden fishing boat,Occupant: Mr. Maciotta,M,...,N,NaN,White shark,A. De Maddalena; Anon. (1938),ND-0028-Maciotta.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0028,ND.0028,29.0
6287,ND.0015,Before 1917,0.0,Unprovoked,FIJI,Moala Island,NaN,Wreck of large double sailing canoe,20 Fijians,NaN,...,Y,NaN,NaN,"Fijian Society papers presented April 17, 1918...",ND-0015-FijianCanoe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0015,ND.0015,16.0
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,...,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0

In [50]:
df["location"].fillna("unknown", inplace=True)

In [51]:
nan_cols = df.isna().sum() # suma de elemento nulos  

nan_cols

case number                  0
date                         0
year                         0
type                         0
country                      0
area                         0
location                     0
activity                   465
name                       168
sex                        501
age                       2480
injury                      22
fatal (y/n)                487
time                      2958
species                   2532
investigator or source      15
pdf                          0
href formula                 1
href                         0
case number.1                0
case number.2                0
original order               0
dtype: int64

In [52]:
df["activity"].fillna("unknown", inplace=True) #relleno  nulos por desconocidos en activity

In [53]:
df[df['name'].isna()] #buscamos el nulo en name
df["name"].fillna("unknown", inplace=True) #relleno  nulos por desconocidos en activity

In [54]:
df.shape

(5832, 22)

In [56]:
df[df['sex'].isna()] #buscamos el nulo en sex
df["sex"].fillna("unknown", inplace=True) #relleno  nulos por desconocidos en activity

In [57]:
df[df['injury'].isna()] #buscamos el nulo en injury
df["injury"].fillna("unknown", inplace=True) #relleno  nulos por desconocidos

In [58]:
df[df['fatal (y/n)'].isna()] #buscamos el nulo en fatal

,case number,date,year,type,country,area,location,activity,name,sex,...,fatal (y/n),time,species,investigator or source,pdf,href formula,href,case number.1,case number.2,original order
27,2018.04.15.c,15-Apr-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,Piedade,Swimming,Pablo de Melo,M,...,NaN,NaN,NaN,"Globo, 4/16/2018",2018.04.15.c-deMelo.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.15.c,2018.04.15.c,6276.0
76,2017.10.01,01-Oct-2017,2017.0,Invalid,SOUTH AFRICA,Western Cape Province,Dyer Island,Scuba Diving,Bradley Fick,M,...,NaN,NaN,Death may have been due to drowning,"All Africa, 10/11/2017",2017.10.01-Fick.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.10.01,2017.10.01,6227.0
79,2017.09.24.b,24-Sep-2017,2017.0,Invalid,USA,New York,Rockaway,Surfing,Michah Behrend,M,...,NaN,15h30,Questionable,"S. Curatolo-Wageman, GSAF",2017.09.24.b-Behrend.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.24.b,2017.09.24.b,6224.0
84,2017.09.15.b,15-Sep-2017,2017.0,Invalid,SOUTH AFRICA,Western Cape Province,Hawston,Scuba Diving,Wayon Love,M,...,NaN,Afternoon,NaN,"Ground Up, 9/20/2017",2017.09.15.b-Love.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.15.b,2017.09.15.b,6219.0
98,2017.08.26.b,26-Aug-2017,2017.0,Invalid,SPAIN,Castellón,Grao de Moncofa,Swimming,female,F,...,NaN,Midday,Shark involvement questionable,"El Periodico Mediterraneo, 8/27/2017",2017.08.26.b-Spain.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.08.26.b,2017.08.26.b,6205.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6104,1826.08.15.R,Reported 15-Aug-1826,1826.0,Unprovoked,ENGLAND,Cumberland,Whitehaven,Bathing,child,unknown,...,NaN,NaN,NaN,"The Times (London), 8/15/1826",1826.08.15.R-Whitehaven.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1826.08.15.R,1826.08.15.R,199.0
6126,1805.09.00,Sep-1805,1805.0,Invalid,USA,New York,"Sag Harbor, Suffolk County",unknown,unknown,M,...,NaN,NaN,Shark involvement prior to death unconfirmed,S.L. Mitchill (1814),1805.09.00-NY.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1805.09.00,1805.09.00,177.0
6147,1767.00.00,1767,1767.0,Invalid,FRANCE,Côte d'Azur,St. Tropez,Bathing,Samuel Matthews,M,...,NaN,NaN,Description of shark does not ring true,NaN,1767.00.00-Matthews.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1767.00.00,1767.00.00,156.0
6157,1733.00.00,1733,1733.0,Invalid,ICELAND,Bardestrand,Talkknefiord,unknown,unknown,unknown,...,NaN,NaN,Shark involvement prior to death unconfirmed,E. Olafsen,1733.00.00-Iceland.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1733.00.00,1733.00.00,146.0
6232,ND.0081,"No date, Before 1963",0.0,Invalid,USA,Hawaii,"Portlock, Oahu",Diving,Val Valentine,M,...,NaN,NaN,Invalid,B. Sojka & D. Lloyd,ND-0081-Valentine.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0081,ND.0081,71.0

In [59]:
df['fatal (y/n)'].unique()

array(['N', 'Y', nan, 'M', 'UNKNOWN', '2017', ' N', 'N '], dtype=object)

In [60]:
df['injury'].unique()

array(['No injury to occupant, outrigger canoe and paddle damaged',
       'Minor injury to left thigh',
       'Injury to left lower leg from surfboard skeg', ...,
       "FATAL, body not recovered but shark was caught with the man's loincloth in its gut shortly afterwards.",
       'FATAL, leg stripped of flesh  ',
       'FATAL. "Shark bit him in half, carrying away the lower extremities" '],
      dtype=object)

In [61]:
df['fatal (y/n)'] = df['fatal (y/n)'].astype(str)

In [62]:
for i, row in df.iterrows():
    if "FATAL" in row['injury'] or 'Y' in row['fatal (y/n)']:
        df.at[i, 'fatal (y/n)'] = 'Y'
    else:
        if 'N' in row['fatal (y/n)']:
            df.at[i, 'fatal (y/n)'] = 'N'
        else:
            df.at[i, 'fatal (y/n)'] = 'UNKNOWN'

In [63]:
df['fatal (y/n)'].unique()

array(['N', 'Y', 'UNKNOWN'], dtype=object)

In [64]:
#Ya no tengo nulos, ahora empiezo a limpiar columnas 
df.head()

,case number,date,year,type,country,area,location,activity,name,sex,...,fatal (y/n),time,species,investigator or source,pdf,href formula,href,case number.1,case number.2,original order
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0

In [65]:
df['year'] = df['year'].astype(str).str.replace('.', '') #le quito los puntos a la columna year
df['year'] = df['year'].astype(str).apply(lambda x: x.rstrip('0')) #y ahora le quito los 0

In [66]:
df_sorted = df.sort_values(by='year', ascending=False)
df_sorted

,case number,date,year,type,country,area,location,activity,name,sex,...,fatal (y/n),time,species,investigator or source,pdf,href formula,href,case number.1,case number.2,original order
6176,0005.00.00,Ca. 5 A.D.,5,Unprovoked,AUSTRALIA,New South Wales,Bondi,unknown,male,M,...,N,NaN,NaN,Waverly Library,0005.00.00-AustralianAboriginal.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,0005.00.00,0005.00.00,127.0
0,2018.06.25,25-Jun-2018,2018,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0
40,2018.02.23,23-Feb-2018,2018,Unprovoked,AUSTRALIA,New South Wales,"Little Congwong Beach, La Perouse",Swimming,Anna Shurapey,F,...,N,"19h00, Dusk","Juvenile white shark, 2.7 to 3.2 m","B. Myatt, GSAF",2018.02.23-Shurapey.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.02.23,2018.02.23,6263.0
28,2018.04.15.b,15-Apr-2018,2018,Unprovoked,AUSTRALIA,Western Australia,"Lefthanders, Margaret River Area",Surfing,Jason Longrass,M,...,N,NaN,NaN,"B.Myatt, GSAF",2018.04.15.b-Longrass.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.15.b,2018.04.15.b,6275.0
29,2018.04.15.a,15-Apr-2018,2018,Unprovoked,AUSTRALIA,Western Australia,"Cobblestones, Margaret River Area",Surfing,Alejandro Travaglini,M,...,N,08h00,NaN,"B.Myatt, GSAF",2018.04.15.a-Travaglini.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.15.a,2018.04.15.a,6274.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6217,ND.0097,No date,,Unprovoked,USA,Florida,"Key West, Monroe County",Kitesurfing,Paul Menta,M,...,N,NaN,NaN,Internet,ND-0097-PaulMenta.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0097,ND.0097,86.0
6216,ND.0100,2003?,,Unprovoked,BAHAMAS,Andros Islands,Great Guana Cay,Spearfishing,C.D. Dollar,M,...,N,NaN,1.8 m [6'] shark,"R.D. Weeks, GSAF",ND-0100-CDDollar.pdf,Q93http://sharkattackfile.net/spreadsheets/pdf...,Q93http://sharkattackfile.net/spreadsheets/pdf...,ND.0100,ND.0100,87.0
6214,ND.0104,1950s,,Unprovoked,AUSTRALIA,Torres Strait,unknown,Helmet diving,male,M,...,N,NaN,Tiger shark,"A. Seekee & R. Callinan, Courier-Mail, 7/7/199...",ND-0104-HelmetDiver.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0104,ND.0104,89.0
6213,ND-0106,Before 1962,,Unprovoked,SOUTH AFRICA,Western Cape Province,"Murray Bay, Robben Island",Swimming,"male, a mental patient",M,...,Y,NaN,NaN,"L.Green, A Decent Fellow doesn't Work, p.225",ND-0106-MentalPatient.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND-0106,ND-0106,90.0
6301,ND.0001,1845-1853,,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,...,Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0

In [67]:
df = df.drop(6176)

In [68]:
df = df.iloc[:-1000]
df

,case number,date,year,type,country,area,location,activity,name,sex,...,fatal (y/n),time,species,investigator or source,pdf,href formula,href,case number.1,case number.2,original order
0,2018.06.25,25-Jun-2018,2018,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0
1,2018.06.18,18-Jun-2018,2018,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0
2,2018.06.09,09-Jun-2018,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0
3,2018.06.08,08-Jun-2018,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0
4,2018.06.04,04-Jun-2018,2018,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5125,1927.07.03,03-Jul-1927,1927,Boating,AUSTRALIA,New South Wales,Bellambi Reef,unknown,"14' boat, occupants: 2 men",unknown,...,N,NaN,NaN,G.P. Whitley; V.M. Coppleson (1933); Note: V.M...,1927.07.03-Bellambi.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1927.07.03,1927.07.03,1178.0
5126,1927.05.29,29-May-1927,1927,Sea Disaster,PHILIPPINES,Luzon Island,Bondoc Peninsula,Sea disaster,Inter island ferry Negros foundered during a t...,unknown,...,Y,NaN,NaN,"The Times (London), 6/2/1927",1927.05.29-Negros.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1927.05.29,1927.05.29,1177.0
5127,1927.05.09.R,Reported 09-May 1927,1927,Unprovoked,AUSTRALIA,Queensland,Off Cairns,Walking,"Quassa, a Torres Strait Islander",M,...,Y,NaN,NaN,"Brisbane Courier, 5/10/1927; V.M. Coppleson (1...",1927.05.09.R-Quassa.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1927.05.09.R,1927.05.09.R,1176.0
5128,1927.04.10,20-Apr-1927,1927,Unprovoked,AUSTRALIA,Torres Strait,Near Thursday Island,Diving,"Napoleon Doola, a Murray Islander)",M,...,N,NaN,NaN,"J. Green, p.32; Bartlett, p. 160; V.M. Copples...",1927.04.10-NapoleonDoola.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1927.04.10,1927.04.10,1175.0
5129,1927.04.08,08-Apr-1927,1927,Unprovoked,AUSTRALIA,Queensland,Near Thursday Island,Pearl diving,Eseromi,M,...,N,NaN,NaN,"J. Green, p.32; V.M. Coppleson (1958), p.241",1927.04.08-Eseromi.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1927.04.08,1927.04.08,1174.0

In [69]:
df["year"].unique()

array(['2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011',
       '201', '2009', '2008', '2007', '2006', '2005', '2004', '2003',
       '2002', '2001', '2', '1999', '1998', '1997', '1996', '1995',
       '1984', '1994', '1993', '1992', '1991', '199', '1989', '1988',
       '1987', '1986', '1985', '1983', '1982', '1981', '198', '1979',
       '1978', '1977', '1976', '1975', '1974', '1973', '1972', '1971',
       '197', '1969', '1968', '1967', '1966', '1965', '1964', '1963',
       '1962', '1961', '196', '1959', '1958', '1957', '1956', '1955',
       '1954', '1953', '1952', '1951', '195', '1949', '1948', '1848',
       '1947', '1946', '1945', '1944', '1943', '1942', '1941', '194',
       '1939', '1938', '1937', '1936', '1935', '1934', '1933', '1932',
       '1931', '193', '1929', '1928', '1927'], dtype=object)

In [70]:
df.loc[df["year"] == '201', "year"] = '2010'
df.loc[df["year"] == '2', "year"] = '2000'
df.loc[df["year"] == '199', "year"] = '1990'
df.loc[df["year"] == '198', "year"] = '1980'
df.loc[df["year"] == '197', "year"] = '1970'
df.loc[df["year"] == '196', "year"] = '1960'

In [71]:
df["year"].unique() #columna YEAR limpia

array(['2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011',
       '2010', '2009', '2008', '2007', '2006', '2005', '2004', '2003',
       '2002', '2001', '2000', '1999', '1998', '1997', '1996', '1995',
       '1984', '1994', '1993', '1992', '1991', '1990', '1989', '1988',
       '1987', '1986', '1985', '1983', '1982', '1981', '1980', '1979',
       '1978', '1977', '1976', '1975', '1974', '1973', '1972', '1971',
       '1970', '1969', '1968', '1967', '1966', '1965', '1964', '1963',
       '1962', '1961', '1960', '1959', '1958', '1957', '1956', '1955',
       '1954', '1953', '1952', '1951', '195', '1949', '1948', '1848',
       '1947', '1946', '1945', '1944', '1943', '1942', '1941', '194',
       '1939', '1938', '1937', '1936', '1935', '1934', '1933', '1932',
       '1931', '193', '1929', '1928', '1927'], dtype=object)

In [74]:
df_sorted

,case number,date,year,type,country,area,location,activity,name,sex,...,fatal (y/n),time,species,investigator or source,pdf,href formula,href,case number.1,case number.2,original order
6176,0005.00.00,Ca. 5 A.D.,5,Unprovoked,AUSTRALIA,New South Wales,Bondi,unknown,male,M,...,N,NaN,NaN,Waverly Library,0005.00.00-AustralianAboriginal.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,0005.00.00,0005.00.00,127.0
0,2018.06.25,25-Jun-2018,2018,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0
40,2018.02.23,23-Feb-2018,2018,Unprovoked,AUSTRALIA,New South Wales,"Little Congwong Beach, La Perouse",Swimming,Anna Shurapey,F,...,N,"19h00, Dusk","Juvenile white shark, 2.7 to 3.2 m","B. Myatt, GSAF",2018.02.23-Shurapey.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.02.23,2018.02.23,6263.0
28,2018.04.15.b,15-Apr-2018,2018,Unprovoked,AUSTRALIA,Western Australia,"Lefthanders, Margaret River Area",Surfing,Jason Longrass,M,...,N,NaN,NaN,"B.Myatt, GSAF",2018.04.15.b-Longrass.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.15.b,2018.04.15.b,6275.0
29,2018.04.15.a,15-Apr-2018,2018,Unprovoked,AUSTRALIA,Western Australia,"Cobblestones, Margaret River Area",Surfing,Alejandro Travaglini,M,...,N,08h00,NaN,"B.Myatt, GSAF",2018.04.15.a-Travaglini.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.15.a,2018.04.15.a,6274.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6217,ND.0097,No date,,Unprovoked,USA,Florida,"Key West, Monroe County",Kitesurfing,Paul Menta,M,...,N,NaN,NaN,Internet,ND-0097-PaulMenta.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0097,ND.0097,86.0
6216,ND.0100,2003?,,Unprovoked,BAHAMAS,Andros Islands,Great Guana Cay,Spearfishing,C.D. Dollar,M,...,N,NaN,1.8 m [6'] shark,"R.D. Weeks, GSAF",ND-0100-CDDollar.pdf,Q93http://sharkattackfile.net/spreadsheets/pdf...,Q93http://sharkattackfile.net/spreadsheets/pdf...,ND.0100,ND.0100,87.0
6214,ND.0104,1950s,,Unprovoked,AUSTRALIA,Torres Strait,unknown,Helmet diving,male,M,...,N,NaN,Tiger shark,"A. Seekee & R. Callinan, Courier-Mail, 7/7/199...",ND-0104-HelmetDiver.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0104,ND.0104,89.0
6213,ND-0106,Before 1962,,Unprovoked,SOUTH AFRICA,Western Cape Province,"Murray Bay, Robben Island",Swimming,"male, a mental patient",M,...,Y,NaN,NaN,"L.Green, A Decent Fellow doesn't Work, p.225",ND-0106-MentalPatient.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND-0106,ND-0106,90.0
6301,ND.0001,1845-1853,,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,...,Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0

In [75]:
df["date"].unique() #Ahora vamos a limpiar el DATE

array(['25-Jun-2018', '18-Jun-2018', '09-Jun-2018', ...,
       'Reported 09-May 1927', '20-Apr-1927', '08-Apr-1927'], dtype=object)

In [76]:
expresion_regular = r'(\d{4})' #Con Regex extraemos el año (4 dígitos)

# Utilizo str.extract para extraer el año y crear la nueva columna 'año'
df['years'] = df['date'].str.extract(expresion_regular)

# Con esto nos aseguramos de que la nueva columna 'years' contiene valores numéricos (no cadenas)
df['years'] = df['years'].astype(float)
df

,case number,date,year,type,country,area,location,activity,name,sex,...,time,species,investigator or source,pdf,href formula,href,case number.1,case number.2,original order,years
0,2018.06.25,25-Jun-2018,2018,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,2018.0
1,2018.06.18,18-Jun-2018,2018,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,2018.0
2,2018.06.09,09-Jun-2018,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,2018.0
3,2018.06.08,08-Jun-2018,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,2018.0
4,2018.06.04,04-Jun-2018,2018,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,2018.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5125,1927.07.03,03-Jul-1927,1927,Boating,AUSTRALIA,New South Wales,Bellambi Reef,unknown,"14' boat, occupants: 2 men",unknown,...,NaN,NaN,G.P. Whitley; V.M. Coppleson (1933); Note: V.M...,1927.07.03-Bellambi.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1927.07.03,1927.07.03,1178.0,1927.0
5126,1927.05.29,29-May-1927,1927,Sea Disaster,PHILIPPINES,Luzon Island,Bondoc Peninsula,Sea disaster,Inter island ferry Negros foundered during a t...,unknown,...,NaN,NaN,"The Times (London), 6/2/1927",1927.05.29-Negros.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1927.05.29,1927.05.29,1177.0,1927.0
5127,1927.05.09.R,Reported 09-May 1927,1927,Unprovoked,AUSTRALIA,Queensland,Off Cairns,Walking,"Quassa, a Torres Strait Islander",M,...,NaN,NaN,"Brisbane Courier, 5/10/1927; V.M. Coppleson (1...",1927.05.09.R-Quassa.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1927.05.09.R,1927.05.09.R,1176.0,1927.0
5128,1927.04.10,20-Apr-1927,1927,Unprovoked,AUSTRALIA,Torres Strait,Near Thursday Island,Diving,"Napoleon Doola, a Murray Islander)",M,...,NaN,NaN,"J. Green, p.32; Bartlett, p. 160; V.M. Copples...",1927.04.10-NapoleonDoola.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1927.04.10,1927.04.10,1175.0,1927.0
5129,1927.04.08,08-Apr-1927,1927,Unprovoked,AUSTRALIA,Queensland,Near Thursday Island,Pearl diving,Eseromi,M,...,NaN,NaN,"J. Green, p.32; V.M. Coppleson (1958), p.241",1927.04.08-Eseromi.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1927.04.08,1927.04.08,1174.0,1927.0

In [77]:
df['years'] = df['years'].astype(str).str.replace('.', '') #le quito los puntos a la columna years
df['years'] = df['years'].astype(str).apply(lambda x: x.rstrip('0')) #y ahora le quito los 0

In [79]:
df['years'].unique()

array(['2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011',
       '2008', '201', '2009', '2006', '2007', '2005', '2004', '2003',
       '2002', '2001', '2', '1999', '1998', '1997', '1996', '1995',
       '1984', '1994', '1993', '1992', '1991', '199', '1989', '1988',
       '1987', '1986', '1985', '1983', '1982', '1981', '198', '1979',
       '1978', '1977', '1976', '1975', '1974', '1973', '1972', '1971',
       '197', '1969', '1968', '1967', '1966', '1965', '1964', '1954',
       '1963', '1962', '1961', '196', '1959', '2176', '1958', '1957',
       '1956', '1955', '1953', '1952', '1951', '195', '1949', '1948',
       '1848', '1947', '1946', '1945', '1944', 'nan', '1943', '1942',
       '1941', '194', '1939', '1938', '1937', '1936', '1935', '1934',
       '1933', '1932', '1931', '193', '1929', '1928', '1927'],
      dtype=object)

In [80]:
df.loc[df["years"] == '201', "years"] = '2010'  #con esto mi nueva columna "years" queda limpia 
df.loc[df["years"] == '2', "years"] = '2000'
df.loc[df["years"] == '199', "years"] = '1990'
df.loc[df["years"] == '198', "years"] = '1980'
df.loc[df["years"] == '197', "years"] = '1970'
df.loc[df["years"] == '196', "years"] = '1960'
df.loc[df["years"] == '194', "years"] = '1940'
df.loc[df["years"] == '195', "years"] = '1950'
df.loc[df["years"] == '193', "years"] = '1930'

In [81]:
df["case number.1"].unique()

array(['2018.06.25', '2018.06.18', '2018.06.09', ..., '1927.05.09.R',
       '1927.04.10', '1927.04.08'], dtype=object)

In [82]:
import re

# Definimos una función para extraer la fecha
def extraer_fecha(texto):
                                                        # Usamos una expresión regular para buscar la fecha en el texto
    fecha = re.search(r'(\d{4}\.\d{2}\.\d{2})', texto)
    if fecha:
        return fecha.group(0)                           # Devuelve la fecha encontrada
    else:
        return None                                     # Devuelve None si no se encuentra una fecha válida

                                                        # Aplicamos la función a la columna y creamos una nueva columna 'fecha_extraida'
df["corrected case number"] = df["case number.1"].apply(extraer_fecha)

# Ahora, la columna 'fecha_extraida' contendrá solo las fechas extraídas

In [83]:
df

,case number,date,year,type,country,area,location,activity,name,sex,...,species,investigator or source,pdf,href formula,href,case number.1,case number.2,original order,years,corrected case number
0,2018.06.25,25-Jun-2018,2018,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,2018,2018.06.25
1,2018.06.18,18-Jun-2018,2018,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,2018,2018.06.18
2,2018.06.09,09-Jun-2018,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,2018,2018.06.09
3,2018.06.08,08-Jun-2018,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,2018,2018.06.08
4,2018.06.04,04-Jun-2018,2018,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,2018,2018.06.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5125,1927.07.03,03-Jul-1927,1927,Boating,AUSTRALIA,New South Wales,Bellambi Reef,unknown,"14' boat, occupants: 2 men",unknown,...,NaN,G.P. Whitley; V.M. Coppleson (1933); Note: V.M...,1927.07.03-Bellambi.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1927.07.03,1927.07.03,1178.0,1927,1927.07.03
5126,1927.05.29,29-May-1927,1927,Sea Disaster,PHILIPPINES,Luzon Island,Bondoc Peninsula,Sea disaster,Inter island ferry Negros foundered during a t...,unknown,...,NaN,"The Times (London), 6/2/1927",1927.05.29-Negros.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1927.05.29,1927.05.29,1177.0,1927,1927.05.29
5127,1927.05.09.R,Reported 09-May 1927,1927,Unprovoked,AUSTRALIA,Queensland,Off Cairns,Walking,"Quassa, a Torres Strait Islander",M,...,NaN,"Brisbane Courier, 5/10/1927; V.M. Coppleson (1...",1927.05.09.R-Quassa.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1927.05.09.R,1927.05.09.R,1176.0,1927,1927.05.09
5128,1927.04.10,20-Apr-1927,1927,Unprovoked,AUSTRALIA,Torres Strait,Near Thursday Island,Diving,"Napoleon Doola, a Murray Islander)",M,...,NaN,"J. Green, p.32; Bartlett, p. 160; V.M. Copples...",1927.04.10-NapoleonDoola.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1927.04.10,1927.04.10,1175.0,1927,1927.04.10
5129,1927.04.08,08-Apr-1927,1927,Unprovoked,AUSTRALIA,Queensland,Near Thursday Island,Pearl diving,Eseromi,M,...,NaN,"J. Green, p.32; V.M. Coppleson (1958), p.241",1927.04.08-Eseromi.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1927.04.08,1927.04.08,1174.0,1927,1927.04.08

In [86]:
nan_cols = df.isna().sum() # suma de elemento nulos  

nan_cols

case number                  0
date                         0
year                         3
type                         0
country                      0
area                         0
location                     0
activity                     0
name                         0
sex                          0
age                       1661
injury                       0
fatal (y/n)                  0
time                      2138
species                   1826
investigator or source      13
pdf                          0
href formula                 1
href                         0
case number.1                0
case number.2                0
original order               0
years                        0
corrected case number        3
month                        3
day                          3
dtype: int64

In [93]:
df = df.dropna(subset=['year', 'investigator or source', 'href formula'])

In [96]:
nan_cols = df.isna().sum() # suma de elemento nulos  

nan_cols

case number               0
date                      0
year                      0
type                      0
country                   0
area                      0
location                  0
activity                  0
name                      0
sex                       0
age                       0
injury                    0
fatal (y/n)               0
time                      0
species                   0
investigator or source    0
pdf                       0
href formula              0
href                      0
case number.1             0
case number.2             0
original order            0
years                     0
corrected case number     0
month                     0
day                       0
dtype: int64

In [97]:
df = df.fillna("unknown") #acabo de rellenar los nulos con unknown
df.shape

(4814, 26)

In [85]:
# Ahora dividimos nuestra nueva columna para sacar meses y dias, lo dividimos en tres partes usando el carácter '.'
import pandas as pd

# Supongamos que tienes un DataFrame df con una columna 'corrected case number'
# Dividir la columna solo si el valor tiene el formato correcto 'YYYY.MM.DD'
def split_date(date_string):
    parts = date_string.split('.') if re.match(r'\d{4}\.\d{2}\.\d{2}', date_string) else [None, None, None]
    return parts

# Aplicar la función a la columna y crear tres nuevas columnas
df[['year', 'month', 'day']] = df['corrected case number'].apply(split_date).apply(pd.Series)

# Convierte las nuevas columnas en tipo numérico si lo deseas
df['year'] = df['year'].astype(float)
df['month'] = df['month'].astype(float)
df['day'] = df['day'].astype(float)

TypeError: expected string or bytes-like object, got 'NoneType'

In [78]:
nan_cols = df.isna().sum() # suma de elemento nulos  

nan_cols

case number                  0
date                         0
year                         0
type                         0
country                      0
area                         0
location                     0
activity                     0
name                         0
sex                          0
age                       1665
injury                       0
fatal (y/n)                  0
time                      2142
species                   1829
investigator or source      13
pdf                          0
href formula                 1
href                         0
case number.1                0
case number.2                0
original order               0
unnamed: 22               4837
unnamed: 23               4837
years                        0
dtype: int64

In [79]:
for i, row in df.iterrows():
    if "FATAL" in row['injury']:
        df.at[i, 'fatal (y/n)'] = 'Y'
    else:
        df.at[i, 'fatal (y/n)'] = 'UNKNOWN'

In [80]:
# Cambiar la configuración para mostrar todas las filas
pd.set_option('display.max_rows', None)

# Luego, ejecuta el código para seleccionar y mostrar las filas duplicadas y las columnas específicas
result = df[df['case number'].duplicated(keep=False)][['case number', 'date', 'year', 'type', 'country', 'area', 'location', 'activity', 'name', 'sex', 'injury', 'fatal (y/n)']]

# Restaura la configuración original
pd.reset_option('display.max_rows')

# Muestra el resultado
print(result)

       case number            date  year        type       country  \
522     2014.08.02     02-Aug-2014  2014  Unprovoked           USA
523     2014.08.02     02-Aug-2014  2014  Unprovoked           USA
615     2013.10.05     06-Oct-2013  2013  Unprovoked           USA
616     2013.10.05     10-Oct-2013  2013  Unprovoked           USA
746   2012.09.02.b     02-Sep-2012  2012  Unprovoked           USA
747   2012.09.02.b     02-Sep-2012  2012    Provoked           USA
1063    2009.12.18     18-Dec-2009  2009  Unprovoked  SOUTH AFRICA
1064    2009.12.18     18-Dec-2009  2009     Invalid  SOUTH AFRICA
1436    2006.09.02     02-Sep-2006  2006  Unprovoked           USA
1437    2006.09.02     02-Sep-2006  2006  Unprovoked  SOUTH AFRICA
1599    2005.04.06     06-Apr-2005  2005  Unprovoked           USA
1600    2005.04.06     06-Apr-2005  2005     Invalid      HONDURAS
2634    1990.05.10     10-May-1990  1990  Unprovoked     AUSTRALIA
2635    1990.05.10     10-May-1990  1990  Unprovoked     AUSTRALIA
3062    1980.07.00   Late Jul-1980  1980  Unprovoked           USA
3063    1980.07.00  Early Jul-1980  1980  Unprovoked           USA
3814  1962.06.11.b     11-Jun-1962  1962  Unprovoked           USA
3815  1962.06.11.b     11-Jun-1962  1962  Unprovoked           USA

                       area  \
522                 Florida
523                 Florida
615              California
616                 Florida
746                 Florida
747                  Hawaii
1063  Eastern Cape Province
1064          KwaZulu-Natal
1436                Florida
1437  Western Cape Province
1599                Florida
1600            Bay Islands
2634             Queensland
2635             Queensland
3062         North Carolina
3063                Florida
3814             California
3815             California

                                               location  \
522                South of Cocoa Beach, Brevard County
523                         Table Beach, Brevard County
615      Bunkers, Humboldt Bay, Eureka, Humboldt County
616                             Destin, Okaloosa County
746                    New Smyrna Beach, Volusia County
747                                Spreckelsville, Maui
1063                       Second Beach, Port St. Johns
1064                                North Beach, Durban
1436                   New Smyrna Beach, Volusia County
1437                                          Noordhoek
1599                   Jacksonville Beach, Duval County
1600                                              Utila
2634               Outer Barrier Reef near Port Douglas
2635               Outer Barrier Reef near Port Douglas
3062  Emerald Isle Pier (near Morehead City), Carter...
3063                   New Smyrna Beach, Volusia County
3814                                  San Francisco Bay
3815                                  San Francisco Bay

                                 activity                      name      sex  \
522                               Surfing                      male        M
523                       Boogie boarding        Christian Sanhueza        M
615                               Surfing              Jay Scrivner        M
616                                Wading  Zachary Tyke Standridge         M
746                       Boogie boarding                    female        F
747                          Spearfishing                M. Malabon  unknown
1063                Paddling on kneeboard       Tshintshekile Nduva        M
1064                              Surfing              Lance Morris        M
1436                             Swimming                      male        M
1437                              Surfing      Steven Harcourt-Wood        M
1599                              unknown               Jessica Abe        F
1600                         SCUBA Diving                    female        F
2634                           Snorkeling              Sydney woman        F
2635  Snorkeling, possibly holding a fish               German male        M
3062                              Surfing                      male        M
3063                              Surfing              Tom Durrance        M
3814              Escaping from Alacatraz           Clarence Anglin        M
3815              Escaping from Alacatraz      John William Anglin         M

                                                 injury fatal (y/n)
522                                         Foot bitten     UNKNOWN
523                                 Laceration to ankle     UNKNOWN
615                                 Laceration to thigh     UNKNOWN
616                       Lacerations to  right forearm     UNKNOWN
746                    Puncture wounds to calf and hand     UNKNOWN
747         Minor laceration to hand  PROVOKED INCIDENT     UNKNOWN
1063                                              FATAL           Y
1064  Minor lacerations to left leg. nitially report...     UNKNOWN
1436                                         Arm bitten     UNKNOWN
1437                  No injury, shark rammed surfboard     UNKNOWN
1599                                  Left calf injured     UNKNOWN
1600  Laceration on siide of calf, small laceration ...     UNKNOWN
2634                                        Lacerations     UNKNOWN
2635                                        Lacerations     UNKNOWN
3062                        No injury, bumped off board     UNKNOWN
3063                                   Lower leg bitten     UNKNOWN
3814                                 2 toes bitten off      UNKNOWN
3815  FATAL, but shark involvement uncomfirmed. Deat...           Y

In [81]:
valores_unicos = df["case number"].unique() # Imprimir todos los valores únicos
for valor in valores_unicos:
    print(valor)

2018.06.25
2018.06.18
2018.06.09
2018.06.08
2018.06.04
2018.06.03.b
2018.06.03.a
2018.05.27
2018.05.26.b
2018.05.26.a
2018.05.24
2018.05.21
2018.05.13.b
2018.05.13.a
2018.05.00
2018.05.12
2018.05.09
2018.04.30.R
2018.04.28.b
2018.04.28.a
2018.04.25.b
2018.04.25.a
2018.04.24
2018.04.23
2018.04.22
2018.04.19
2018.04.15.d
2018.04.15.c
2018.04.15.b
2018.04.15.a
2018.04.14
2018.04.10.R
2018.04.03
2018.03.31
2018.03.14
2018.03.09.b
2018.03.09.a
2018.02.24
2018.02.23
2018.02.17
2018.02.15
2018.02.14
2018.02.11
2018.02.03
2018.02.01
2018.01.28
2018.01.14
2018.01.13
2018.01.12
2018.01.05
2017.12.31
2017.12.30
2017.12.21
2017.11.30.b
2017.11.30.a
2017.11.24
2017.11.18
2017.11.13
2017.11.04
2017.10.31.R
2017.10.28
2017.10.26
2017.10.23.c
2017.10.23.b
2017.10.23.a
2017.10.22
2017.10.21
2017.10.18
2017.10.09
2017.10.05
2017.10.01
2017.09.25.b
2017.09.25.a
2017.09.24.b
2017.09.24.a
2017.09.20
2017.09.16.b
2017.09.16.a
2017.09.15.b
2017.09.15.a
2017.09.14
2017.09.13
2017.09.10.b
2017.09.10.a
2017.09.03.b
2017.09.03.a
2017.09.02.c
2017.09.02.b
2017.09.02.a
2017.08.29
2017.08.27
2017.08.26.b
2017.08.26.a
2017.08.23
2017.08.10
2017.08.05
2017.08.03
2017.08.01
2017.07.31
2017.07.29.c
2017.07.29.a
2017.07.27
2017.07.26.R
2017.07.24
2017.07.23.b
2017.07.23.a
2017.07.22
2017.07.20.c
2017.07.20.b
2017.07.20.a
2017.07.14.b
2017.07.14.a
2017.07.11
2017.07.09
2017.07.07.R
2017.07.07
2017.07.02
2017.06.29
2017.06.21
2017.06.19
2017.06.18.b
2017.06.17
2017.06.05
2017.06.11
2017.06.10.b
2017.06.10.a
2017.06.07.R
2017.06.04
2017.06.02
2017.05.30
2017.05.28
2017.05.27
2017.05.12
2017.05.06.R
2017.05.06
2017.05.03
2017.04.29.d
2017.04.29.c
2017.04.29.b
2017.04.29.a
2017.04.27
2017.04.26
2017.04.22
2017.04.20
2017.04.17.b
2017.04.17.a
2017.04.14
2017.04.13
2017.04.12.b
2017.04.12.a
2017.04.11
2017.04.10.b
2017.04.10.a
2017.04.06
2017.04.05
2017.04.02.b
2017.04.02.a
2017.03.27
2017.03.19
2017.03.18
2017.03.11
2017.03.09
2017.02.25
2017.02.24
2017.02.21
2017.02.17
2017.02.11
2017.02.06.b
2017.02.06.a
2017.02.01.b
2017.02.01.a
2017.01.24
2017.01.22
2017.01.21
2017.01.13.b
2017.01.13.a
2017.01.09
2017.01.08.R
2017.01.05
2017.01.03
2016.12.27
2016.12.24
2016.12.19
2016.12.14
2016.12.11.b
2016.12.11.a
2016.12.06
2016.12.01
2016.11.28
2016.11.14
2016.10.30
2016.10.29
2016.10.24
2016.10.21
2016.10.15
2016.10.14
2016.10.12
2016.10.10
2016.10.02
2016.10.01
2016.09.26
2016.09.18.c
2016.09.18.b
2016.09.18.a
2016.09.17.b
2016.09.17.a
2016.09.15
2016.09.15.R
2016.09.11
2016.09.07
2016.09.06
2016.09.05.b
2016.09.05.a
2016.09.04
2016.09.01
2016.08.29.b
2016.08.29.a
2016.08.25
2016.08.07
2016.08.06
2016.08.04
2016.07.29
2016.07.28.R
2016.07.28
2016.07.27
2016.07.26
2016.07.24
2016.07.23.b
2016.07.23.a
2016.07.20
2016.07.17
2016.07.16.b
2016.07.16.a
2016.07.15.b
2016.07.15.a
2016.07.08.R
2016.07.08
2016.07.07.b
2016.07.07.a
2016.07.06
2016.07.04
2016.06.27
2016.06.25
2016.06.24
2016.06.23
2016.06.21.b
2016.06.21.a
2016.06.15.b
2016.06.15.a
2016.06.14
2016.06.11
2016.06.07
2016.06.05.b
2016.06.05.a
2016.06.04
2016.06.02.b
2016.05.31
2016.05.29.b
2016.05.29.a
2016.05.22
2016.05.21.b
2016.05.21.a
2016.05.18
2016.05.15
2016.05.03
2016.05.02
2016.04.25
2016.04.23
2016.04.22
2016.04.19
2016.04.18.b
2016.04.18.a
2016.04.13
2016.04.09
2016.04.08
2016.04.07.b
2016.04.07.a
2016.03.31
2016.03.30
2016.03.28.b
2016.03.28.a
2016.03.13
2016.03.11
2016.03.10
2016.03.04
2016.03.03.R
2016.03.02
2016.02.22
2016.02.19
2016.02.12
2016.02.10.R
2016.02.10
2016.02.05
2016.02.04
2016.02.02
2016.01.29
2016.01.28
2016.01.25
2016.01.24.b
2016.01.24.a
2016.01.23
2016.01.11.R
2016.01.05
2016.01.02
2015.12.26
2015.12.25
2015.12.22
2015.12.21.b
2015.12.21.a
2015.12.13
2015.12.08
2015.11.20
2015.11.16
2015.11.15.b
2015.11.15.a
2015.11.10
2015.12.23
2015.11.03
2015.11.01.b
2015.11.01.a
2015.10.30
2015.10.28.a
2015.10.25
2015.10.21
2015.10.19
2015.10.17.c
2015.10.17.b
2015.10.17.a
2015.10.13
2015.10.09.b
2015.10.09.a
2015.10.08
2015.10.07
2015.10.05.b
2015.10.05.a
2015.10.04
2015.09.29
2015.09.26
2015.09.24
2015.09.20.d
2015.09.20.c
2015.09.20.b
2015.09.20.a
2015.09.19
2015.09.18
2015.09.17
2015.09.08
2015.09.06
2015.09.05
2015.09.04
2015.09.03
2015.09.01
2015.08.29.b
2015.08.29.a
2015.08.22.b
2015.08.22.a
2015.08.20
2015.08.19
2015.08.18.b
2015.08.18.a
2015.08.10
2015.07.31
2015.07.28
2015.07.27
2015.07.26.b
2015.07.26.a
2015.07.25
2015.07.23.b
2015.07.23.a
2015.07.19
2015.07-10
2015.07.08
2015.07.06
2015.07.04.b
2015.07.04.a
2015.07.03
2015.07.02
2015.07.01
2015.06.30.b
2015.06.30.a
2015.06.27.b
2015.06.27.a
2015.06.26.c
2015.06.26.b
2015.06.26.a
2015.06.25.R
2015.06.25
2015.06.24.b
2015.06.24.a
2015.06.23
2015.06.17
2015.06.14.b
2015.06.14.a
2015.06.13
2015.06.11
2015.06.07
2015.06.05
2015.06.01
2015.05.29.b
2015.05.29.a
2015.05.25
2015.05.24
2015.05.20
2015.05.15
2015.05.07
2015.05.03
2015.05.02
2015.04.29
2015.04.26
2015.04.25
2015.04.24.c
2015.04.13
2015.04.12
2015.04.11
2015.04.03
2015.03.29
2015.03.31
2015.03.26
2015.03.18
2015.03.16
2015.03.11
2015.03.10
2015.03.07
2015.02.14
2015.02.09
2015.02.08
2015.02.05
2015.01.30
2015.01.27
2015.01.24
2015.01.23
2015.01.19.b
2015.01.19.a
2015.01.17
2015.01.16
2015.01.08
2015.01.06
2015.01.03
2015.01.01
2014.12.29.b
2014.12.29.a
2014.12.28.c
2014.12.28.b
2014.12.28.a
2014.12.15
2014.12.03.R
2014.11.29
2014.11.20
2014.11.19
2014.11.17
2014.11.16
2014.11.13
2014.11.10
2014.11.08
2014.10.31
2014.10.30
2014.10.22
2014.10.20
2014.10.19
2014.10.18
2014.10.17
2014.10.14
2014.10.12
2014.10.11
2014.10.05.b
2014.10.07
2014.10.05.a
2014.10.03.b
2014.10.03.a
2014.10.02.b
2014.10.02.a
2014.09.21
2014.09.13.R
2014.09.13
2014.09.09
2014.09.06
2014.09.03
2014.09.02
2014.09.00
2014.08.31
2014.08.29.b
2014.08.29.a
2014.08.28
2014.08.27.c
2014.08.27.b
2014.08.27.a
2014.08.25
2014.08.24
2014.08.16
2014.08.12
2014.08.10
2014.08.09
2014.08.08
2014.08.06
2014.08.05
2014.08.02
2014.08.01
2014.07.27
2014.07.22
2014.07.21
2014.07.20
2014.07.16
2014.07.14
2014.07.13
2014.07.12
2014.07.09
2014.07.05.b
2014.07.05.a
2014.07.03
2014.06.25
2014.06.18.b
2014.06.18.a
2014.06.17.R
2014.06.09.b
2014.06.09.a
2014.06.08
2014.06.07
2014.06.01.c
2014.06.01.b
2014.06.01.a
2014.05.27.R
2014.05.23
2014.05.22
2014.05.15
2014.05.14
2014.05.13
2014.05.11
2014.05.10.R
2014.05.06
2014.05.04
2014.05.01
2014.04.24
2014.04.22
2014.04.15
2014.04.12
2014.04.04.b
2014.04.04.a
2014.04.03
2014.03.29
2014.03.22.b
2014.03.22.a
2014.03.21
2014.03.18.c
2014.03.18.b
2014.03.18
2014.03.12
2014.03.02
2014.02.20
2014.02.08
2014.02.07.b
2014.02.07
2014.01.26
2014.01.25
2014.01.04
2014.00.00.b
2013.12.25
2013.12.16
2013.12.13
2013.12.11
2013.12.10
2013.12.05
2013.12.02
2013.11.30
2013.11.29
2013.11.23.a
2013.11.22
2013.11.12
2013.11.07.b
2013.11.07.a
2013.10.31
2013.10.28
2013.10.26.b
2013.10.26.a
2013.10.24
2013.10.23
2013.10.20
2013.10.19
2013.10.11
2013.10.08
2013.10.05
2013.09.29.b
2013.09.29.a
2013.09.25
2013.09.21.b
2013.09.21.a
2013.09.14
2013.09.12
2013.09.08
2013.09.07.b
2013.09.07.a
2013.09.02
2013.09.01.c
2013.09.01.a
2013.08.31.a
2013.08.29
2013.08.26
2013.08.25.b
2013.08.25
2013.08.18
2013.08.17
2013.08.14
2013.08.13
2013.08.11
2013.08.05
2013.07.31
2013.07.30
2013.07.29.c
2013.07.29.b
2013.07.29.a
2013.07.28.b
2013.07.28.a
2013.07.22
2013.07.19
2013.07.17.R
2013.07.15
2013.07.11
2013.07.09
2013.07.02
2013.06.30
2013.06.27
2013.06.25.c
2013.06.25.b
2013.06.25.a
2013.06.18
2013.06.17
2013.06.16
2013.06.15
2013.06.14.R
2013.06.06.b
2013.06.06.a
2013.05.27.b
2013.05.27.a
2013.05.23.b
2013.05.14
2013.05.08.b
2013.05.08.a
2013.05.04.a
2013.04.28
2013.04.24
2013.04.21
2013.04.17
2013.04.14
2013.04.13.b
2013.04.10
2013.04.04
2013.04.02.R
2013.04.02.a
2013.03.31
2013.03.21
2013.03.16.b
2013.03.16.a
2013.03.12
2013.03.10.b
2013.03.10.a
2013.03.03
2013.02.27
2013.02.21.b
2013.02.21.a
2013.02.10
2013.02.09
2013.02.01
2013.01.26
2013.01.25
2013.01.21.R
2013.01.16
2013.01.13
2013.01.05
2012.12.31
2012.12.30
2012.12.28
2012.12.25
2012.12.19
2012.12.05
2012.12.02
2012.12.00
2012.11.30
2012.11.27
2012.11.22
2012.11.19
2012.11.04.b
2012.11.04.a
2012.10.30
2012.10.27
2012.10.23
2012.10.19
2012.10.18.b
2012.10.18.a
2012.10.16
2012.10.11.R
2012.10.07
2012.10.02
2012.09.25
2012.09.24
2012.09.16
2012.09.10
2012.09.09
2012.09.08.b
2012.09.08.a
2012.09.06.b
2012.09.06.a
2012.09.04
2012.09.02.b
2012.09.02.a
2012.08.31
2012.08.28
2012.08.26
2012.08.15
2012.08.11
2012.08.09
2012.08.05
2012.08.04
2012.07.31.b
2012.07.31.a
2012.07.30.b
2012.07.30.a
2012.07.24
2012.07.23
2012.07.21
2012.07.19
2012.07.14
2012.07.08
2012.07.07.c
2012.07.07.b
2012.07.07.a
2012.07.06
2012.06.26.c
2012.06.26.b
2012.06.26.a
2012.06.22.b
2012.06.22.a
2012.06.20
2012.06.19
2012.06.18
2012.06.15
2012.06.14.d
2012.06.14.c
2012.06.14.b
2012.06.14.a
2012.06.12
2012.06.10
2012.06.03
2012.06.02.b
2012.06.02.a
2012.05.31
2012.05.29
2012.05.23
2012.05.20
2012.05.12
2012.05.09
2012.05.06
2012.04.19.b
2012.04.19.a
2012.04.11
2012.04.03
2012.04.00
2012.03.31
2012.03.24
2012.03.22
2012.03.20
2012.03.15
2012.03.14.b
2012.03.14.a
2012.03.06.b
2012.03.06.a
2012.03.05
2012.03.04
2012.03.03
2012.03.01
2012.02.26
2012.02.25
2012.02.20
2012.02.06
2012.01.27
2012.01.19
2012.01.18.b
2012.01.18.a
2012.01.15
2012.01.13
2012.01.03
2012.01.02
2011.12.31
2011.12.26.R
2011.12.25
2011.12.23
2011.12.21.b
2011.12.21.a
2011.12.11
2011.12.07.b
2011.12.07.a
2011.12.06
2011.12.05
2011.12.02
2011.11.29
2011.11.28
2011.11.22
2011.11.20.R
2011.11.12
2011.11.11
2011.10.29.
2011.10.28.R
2011.10.28.
2011.10.22
2011.10.20
2011.10.19
2011.10.11
2011.10.10
2011.10.09
2011.10.02
2011.10.01
2011.09.30
2011.09.28.b
2011.09.28.a
2011.09.24.b
2011.09.24.a
2011.09.20
2011.09.19
2011.09.17
2011.09.16
2011.09.11.b
2011.09.11.a
2011.09.04.b
2011.09.04.a
2011.09.02
2011.08.31
2011.08.28.b
2011.08.28.a
2011.08.26
2011.08.24.b
2011.08.24.a
2011.08.23
2011.08.18
2011.08.17.c.
2011.08.17.b.
2011.08.17.a
2011.08.16.c
2011.08.16.b
2011.08.16.a
2011.08.15
2011.08.11
2011.08.01
2011.07.31
2011.07.25
2011.07.22
2011.07.19
2011.07.15
2011.07.13.b
2011.07.13.a
2011.07.07.b
2011.07.07.a
2011.07.06
2011.07.05
2011.06.30
2011.06.29
2011.06.28
2011.06.26
2011.06.24
2011.06.21
2011.06.19.b
2011.06.19.a
2011.06.15
2011.06.14.R
2011.06.12
2011.06.06.R
2011.06.06.b
2011.06.06.a
2011.06.01
2011.05.30
2011.05.29
2011.05.25
2011.05.22
2011.05.21.b
2011.05.13.b
2011.05.21.a
2011.05.13.a
2011.05.10
2011.05.07.R
2011.05.04
2011.04.26
2011.04.23
2011.04.22
2011.04.16
2011.04.12
2011.04.08
2011.03.29.R
2011.03.24
2011.03.23
2011.03.21.b
2011.03.16
2011.03.10.R
2011.03.10
2011.02.28.R
2011.02.23
2011.02.19
2011.02.17
2011.02.13
2011.02.12
2011.02.04.R
2011.02.02
2011.01.31
2011.01.28
2011.01.26
2011.01.20
2011.01.15
2011.01.12.R
2011.01.03
2010.12.26
2010.12.17
2010.12.11
2010.12.05
2010.12.03.R
2010.12.01.b
2010.12.01.a
2010.11.30.b
2010.11.30.a
2010.11.27
2010.11.19
2010.11.14
2010.11.12.R
2010.10.30
2010.10.28.R
2010.10.28
2010.10.23.b
2010.10.23.a
2010.10.22
2010.10.20
2010.10.09
2010.10.02.b
2010.10.02.a
2010.10.01
2010.09.27
2010.09.24
2010.09.21
2010.09.13
2010.09.07
2010.09.06.R
2010.09.04
2010.09.03.b
2010.09.03.a
2010.09.02
2010.08.29
2010.08.18
2010.08.17
2010.08.14
2010.08.10.b
2010.08.10
2010.08.08
2010.08.07.b
2010.08.05
2010.08.02.b
2010.08.02.a
2010.07.25
2010.07.23
2010.07.19
2010.07.17.b
2010.07.17.a
2010.07.16.b
2010.07.16.a
2010.07.11
2010.07.04
2010.07.03
2010.07.02.b
2010.07.02.a
2010.06.27
2010.06.25.b
2010.06.25.a
2010.06.15
2010.06.10
2010.06.06
2010.06.00
2010.05.30
2010.05.18.c
2010.05.18.b
2010.05.18.a
2010.05.03
2010.05.01
2010.04.28
2010.04.19
2010.04.13
2010.04.04
2010.03.27
2010.02.19
2010.02.16
2010.02.15
2010.02.13
2010.02.11
2010.02.06.R
2010.02.06.b
2010.02.06.a
2010.02.04
2010.02.03
2010.02.01
2010.01.30
2010.01.27
2010.01.22.b
2010.01.22.a
2010.01.12
2010.01.09.d
2010.01.09.c
2010.01.09.b
2010.01.09.a
2010.01.06
2010.01.05
2009.12.29
2009.12.26
2009.12.22
2009.12.20.b
2009.12.20.a
2009.12.18
2009.12.16
2009.12.13
2009.12.12
2009.12.06
2009.11.25
2009.11.24
2009.11.16.b
2009.11.16.a
2009.11.13
2009.11.11
2009.11.08
2009.11.05
2009.10.30
2009.10.29.R
2009.10.28
2009.10.24
2009.10.19
2009.10.18
2009.10.17
2009.10.14.R
2009.10.09
2009.10.02
2009.09.26
2009.09.13
2009.09.12
2009.09.07
2009.09.01
2009.08.30
2009.08.29
2009.08.25
2009.08.11
2009.08.10
2009.08.06
2009.08.01
2009.07.31
2009.07.30
2009.07.29
2009.07.24.R
2009.07.24.b
2009.07.24.a
2009.07.22.b
2009.07.22.a
2009.07.18
2009.07.11.a
2009.07.07
2009.07.05
2009.07.04
2009.06.27
2009.06.21
2009.06.16
2009.06.02.b
2009.06.02.a
2009.06.01
2009.05.31
2009.05.25
2009.05.17
2009.05.16.b
2009.05.16.a
2009.05.12
2009.05.06
2009.04.28
2009.04.25.R
2009.04.21
2009.04.20
2009.04.19
2009.04.17.
2009.04.11
2009.04.12
2009.04.06.b
2009.04.06.a
2009.04.03
2009.03.27
2009.03.21
2009.03.20
2009.03.19.b
2009.03.19.a
2009.03.18.a
2009.03.17.R
2009.03.17
2009.03.16.R
2009.03.06
2009.03.02
2009.03.01.b
2009.03.01.a
2009.02.22
2009.02.18
2009.02.12
2009.02.11
2009.02.08
2009.02.07.b
2009.02.07.a
2009.01.25
2009.01.24.c
2009.01.24.b
2009.01.24.a
2009.01.23
2009.01.18
2009.01.16
2009.01.13.R
2009.01.12
2009.01.11.b
2009.01.11.a
2009.01.10.R
2009.01.10.a
2009.01.06
2009.01.00
2008.12.30
2008.12.27.d
2008.12.27.c
2008.12.27.b
2008.12.27.a
2008.12.20
2008.12.14
2008.12.10
2008.12.06
2008.12.00
2008.11.28
2008.11.25
2008.11.24
2008.11.09.b
2008.11.06
2008.10.22
2008.10.12
2008.10.11
2008.10.08
2008.10.06
2008.09.28.b
2008.09.28.a
2008.09.15
2008.09.14
2008.09.09
2008.09.08
2008.09.07
2008.09.06.b
2008.09.06.a
2008.09.01
2008.09.00
2008.08.30.c
2008.08.30.b
2008.08.30.a
2008.08.28
2008.08.27
2008.08.24
2008.08.22
2008.08.20
2008.08.18
2008.08.16
2008.08.12
2008.08.11
2008.07.30.R
2008.07.27
2008.07.26.b
2008.07.26.a
2008.07.25.b
2008.07.25.a
2008.07.24.b
2008.07.24.a
2008.07.23
2008.07.19
2008.07.13
2008.07.11
2008.07.09
2008.07.05
2008.07.00
2008.06.28.c
2008.06.28.b
2008.06.28.a
2008.06.26.R
2008.06.26.b
2008.06.26.a
2008.06.24
2008.06.21
2008.06.20
2008.06.11
2008.06.07
2008.06.02.R
2008.06.01.b
2008.06.01.a
2008.05.26
2008.05.24.b
2008.05.24.a
2008.05.23
2008.05.14
2008.05.10
2008.05.07.b
2008.05.07.a
2008.04.28.b
2008.04.28.a
2008.04.27
2008.04.26.b
2008.04.26.a
2008.04.25
2008.04.20.b
2008.04.20.a
2008.04.19.R
2008.04.18
2008.04.17
2008.04.15
2008.03.25
2008.04.08.R
2008.04.08
2008.04.03
2008.03.28.c
2008.03.28.b
2008.03.28.a
2008.03.23
2008.03.21
2008.03.15
2008.03.07
2008.02.24
2008.02.21.R
2008.02.15
2008.02.07
2008.02.06
2008.01.30
2008.01.29
2008.01.27
2008.01.19.R
2008.01.14
2008.01.10
2008.00.00.b
2008.00.00.a
2007.12.21
2007.12.19
2007.12.18
2007.12.15
2007.12.14
2007.12.10
2007.12.09
2007.12.07
2007.11.18
2007.11.08
2007.11.07
2007.11.06
2007.11.04
2007.11.03
2007.11.00
2007.10.29
2007.10.15
2007.10.13
2007.10.07
2007.10.06
2007.09.30.c
2007.09.30.b
2007.09.30.a
2007.09.28
2007.09.27.b
2007.09.27.a
2007.09.22.b
2007.09.22.a
2007.09.20
2007.09.17
2007.09.16.b
2007.09.16.a
2007.09.13
2007.09.08
2007.09.05
2007.09.04
2007.09.03.b
2007.09.03.a
2007.08.28.b
2007.08.28.a
2007.08.26
2007.08.25
2007.08.22
2007.08.20
2007.08.19.c
2007.08.19.b
2007.08.19.a.
2007.08.15
2007.08.12
2007.08.11
2007.08.09.b
2007.08.09.a
2007.08.07
2007.07.29
2007.07.28
2007.07.22
2007.07.21
2007.07.19.b
2007.07.19.a
2007.07.18.b
2007.07.18.a
2007.07.17.b
2007.07.17.a
2007.07.10
2007.07.05
2007.06.30.b
2007.06.30.a
2007.06.25
2007.06.24
2007.06.17
2007.06.12
2007.06.05
2007.05.26
2007.05.24
2007.05.17.R
2007.05.16
2007.05.12
2007.05.10
2007.05.09.R
2007.05.08
2007.05.07.b
2007.05.07.a
2007.05.04
2007.05.00
2007.04.26
2007.04.22
2007.04.20
2007.04.13.R
2007.04.09
2007.04.01
2007.03.31.b
2007.03.31.a
2007.03.22
2007.03.21
2007.03.20
2007.03.14.R
2007.03.12
2007.03.11
2007.03.05.R
2007.02.03
2007.02.00
2007.01.25.b
2007.01.25.a
2007.01.23
2007.01.19
2007.01.14
2007.01.09
2007.01.07
2007.01.05
2006.12.18
2006.12.11
2006.12.10
2006.12.06
2006.12.02
2006.11.25
2006.11.11
2006.11.09
2006.10.31
2006.10.16
2006.10.10
2006.10.07
2006.10.05
2006.10.00.b
2006.10.00.a
2006.09.30
2006.09.29
2006.09.18.R
2006.09.16
2006.09.14
2006.09.11
2006.09.04
2006.09.03.a
2006.09.02
2006.08.29.b
2006.08.29.a
2006.08.27
2006.08.22.b
2006.08.22.a
2006.08.20.a
2006.08.15
2006.08.13
2006.08.00.b
2006.07.31.R
2006.07.31.a
2006.07.29.b
2006.07.29.a
2006.07.28
2006.07.25
2006.07.23
2006.07.17.R
2006.07.17
2006.07.13
2006.07.12
2006.07.10
2006.07.09.b
2006.07.09.a
2006.07.08.b
2006.07.08.a
2006.06.30.b
2006.06.30.a
2006.06.27
2006.06.26
2006.06.24
2006.06.20
2006.06.18
2006.06.17
2006.06.15
2006.06.07
2006.06.05
2006.05.31
2006.05.28
2006.05.27
2006.05.24
2006.05.21
2006.05.19
2006.05.10
2006.05.04
2006.05.02
2006.04.23.R
2006.04.21
2006.04.19
2006.04.13
2006.04.11
2006.04.09.b
2006.04.09.a
2006.04.03
2006.03.28.R
2006.03.23
2006.03.22
2006.03.19
2006.03.15
2006.02.27
2006.02.23
2006.02.13
2006.02.12.b
2006.02.12.a
2006.02.08
2006.02.01.b
2006.02.01.a
2006.01.28.R
2006.01.25
2006.01.23
2006.01.18
2006.01.15
2006.01.11
2006.01.07
2006.01.04
2006.01.01
2005.12.24
2005.12.21
2005.12.20
2005.12.11
2005.12.05.R
2005.11.29.R
2005.11.27
2005.11.25.c
2005.11.25.b
2005.11.25.a
2005.11.24
2005.11.21
2005.11.20
2005.11.15
2005.11.12
2005.11.02.b
2005.11.02.a
2005.10.29
2005.10.25
2005.10.22
2005.10.21
2005.10.19
2005.10.15
2005.10.13
2005.10.11
2005.10.06
2005.10.03
2005.10.01
2005.09.27.R
2005.09.24
2005.09.23
2005.09.22
2005.09.20
2005.09.11
2005.09.07
2005.09.05
2005.09.04.a
2005.09.02.b
2005.08.24.b
2005.08.24.a
2005.08.22
2005.08.21
2005.08.19
2005.08.14
2005.08.12
2005.08.06
2005.08.01
2005.07.27
2005.07.23
2005.07.22
2005.07.17.a
2005.07.15
2005.07.13
2005.07.01
2005.06.27
2005.06.25
2005.06.22
2005.06.21
2005.06.18
2005.06.16
2005.06.13
2005.06.07
2005.06.05
2005.06.04
2005.06.02
2005.05.28
2005.05.27
2005.05.25
2005.05.15
2005.05.14
2005.05.02.R
2005.05.02
2005.04.25
2005.04.17.R
2005.04.16.b
2005.04.16.a
2005.04.13
2005.04.09
2005.04.07
2005.04.06
2005.03.28
2005.03.27.R
2005.03.19
2005.03.12
2005.03.10
2005.03.09
2005.03.05
2005.02.26
2005.02.22
2005.02.16
2005.02.13
2005.02.04
2005.01.20
2005.01.19
2005.01.14
2005.01.08
2004.12.26
2004.12.16
2004.12.11
2004.11.27
2004.11.26
2004.11.15
2004.11.11.b
2004.11.11.a
2004.11.00
2004.10.31
2004.10.30.x
2004.10.30.a
2004.10.21
2004.10.10
2004.10.09.b
2004.10.09.a
2004.10.06
2004.10.02
2004.10.01
2004.09.25
2004.09.20
2004.09.10
2004.09.08
2004.09.04
2004.08.29
2004.08.21
2004.08.20
2004.08.15
2004.08.06
2004.08.03
2004.08.00
2004.07.31
2004.07.30
2004.07.28
2004.07.27.b
2004.07.27.a
2004.07.25
2004.07.19.R
2004.07.15
2004.07.10
2004.07.02.b
2004.07.02.a
2004.06.26.b
2004.06.26.a
2004.06.14
2004.06.10.b
2004.06.10.a
2004.06.02
2004.05.29
2004.05.23.b
2004.05.28
2004.05.23.a
2004.05.22.c
2004.05.22.b
2004.05.22.a
2004.05.18
2004.05.04
2004.05.01
2004.04.26
2004.04.22
2004.04.13.b
2004.04.13.a
2004.04.07
2004.04.05
2004.04.04
2004.03.31.b
2004.03.31.a
2004.03.29
2004.03.28
2004.03.27.b
2004.03.27.a
2004.03.24
2004.03.22
2004.03.16
2004.03.06
2004.02.29
2004.02.26
2004.02.21
2004.02.16
2004.02.11
2004.01.25
2004.01.23
2004.01.22
2004.01.21.b
2004.01.21.a
2004.01.15.R
2004.01.12
2004.01.07
2004.01.03.b
2004.01.03.a
2004.00.00
2003.12.31
2003.12.26
2003.12.13.b
2003.12.13.a
2003.12.08
2003.11.30.b
2003.11.30.a
2003.11.27
2003.11.22
2003.11.12.b
2003.11.12.a
2003.11.06.b
2003.11.06.a
2003.11.01
2003.11.00
2003.10.31.c
2003.10.31.b
2003.10.31.a
2003.10.27
2003.10.24
2003.10.14
2003.10.06
2003.10.05.e
2003.10.05.d
2003.10.05.c
2003.10.05.b
2003.10.05.a
2003.09.29
2003.09.28
2003.09.21
2003.09.19
2003.09.17
2003.09.14.c
2003.09.14.b
2003.09.14.a
2003.09.13.b
2003.09.13.a
2003.09.12
2003.09.00
2003.08.29
2003.08.19
2003.08.12
2003.08.08
2003.07.26.R
2003.07.20
2003.07.15
2003.07.09
2003.07.05.b
2003.07.05.a
2003.07.04
2003.07.00.c
2003.07.00.b
2003.07.00.a
2003.06.30
2003.06.26
2003.06.24.c
2003.06.24.b
2003.06.24.a
2003.06.22
2003.06.19
2003.06.08
2003.06.00
2003.05.25
2003.05.14
2003.05.10
2003.05.07
2003.05.03
2003.05.00
2003.04.26
2003.04.25
2003.04.23.b
2003.04.23.a
2003.04.21.b
2003.04.21.a
2003.04.20.c
2003.04.20.b
2003.04.20.a
2003.04.19
2003.04.18
2003.04.15
2003.04.11
2003.04.09

In [82]:
df["year"].unique()

array(['2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011',
       '2010', '2009', '2008', '2007', '2006', '2005', '2004', '2003',
       '2002', '2001', '2000', '1999', '1998', '1997', '1996', '1995',
       '1984', '1994', '1993', '1992', '1991', '1990', '1989', '1988',
       '1987', '1986', '1985', '1983', '1982', '1981', '1980', '1979',
       '1978', '1977', '1976', '1975', '1974', '1973', '1972', '1971',
       '1970', '1969', '1968', '1967', '1966', '1965', '1964', '1963',
       '1962', '1961', '1960', '1959', '1958', '1957', '1956', '1955',
       '1954', '1953', '1952', '1951', '195', '1949', '1948', '1848',
       '1947', '1946', '1945', '1944', '1943', '1942', '1941', '194',
       '1939', '1938', '1937', '1936', '1935', '1934', '1933', '1932',
       '1931', '193', '1929', '1928', '1927'], dtype=object)

In [83]:
filas_con_año_500 = df[df['year'] == 500]
filas_con_año_500

Empty DataFrame
Columns: [case number, date, year, type, country, area, location, activity, name, sex, age, injury, fatal (y/n), time, species, investigator or source, pdf, href formula, href, case number.1, case number.2, original order, unnamed: 22, unnamed: 23, years]
Index: []

[0 rows x 25 columns]

In [84]:
df['year'] = df['year'].astype(str).str.replace('.', '') #le quito los puntos
df['year'] = df['year'].astype(str).str.replace('20180', '2018') 
df['year']

0       2018
1       2018
2       2018
3       2018
4       2018
        ...
5132    1927
5133    1927
5134    1927
5135    1927
5136    1927
Name: year, Length: 4838, dtype: object

In [85]:
df['year'] = df['year'].astype(str).apply(lambda x: x.rstrip('0'))

In [86]:
df["year"].unique()

array(['2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011',
       '201', '2009', '2008', '2007', '2006', '2005', '2004', '2003',
       '2002', '2001', '2', '1999', '1998', '1997', '1996', '1995',
       '1984', '1994', '1993', '1992', '1991', '199', '1989', '1988',
       '1987', '1986', '1985', '1983', '1982', '1981', '198', '1979',
       '1978', '1977', '1976', '1975', '1974', '1973', '1972', '1971',
       '197', '1969', '1968', '1967', '1966', '1965', '1964', '1963',
       '1962', '1961', '196', '1959', '1958', '1957', '1956', '1955',
       '1954', '1953', '1952', '1951', '195', '1949', '1948', '1848',
       '1947', '1946', '1945', '1944', '1943', '1942', '1941', '194',
       '1939', '1938', '1937', '1936', '1935', '1934', '1933', '1932',
       '1931', '193', '1929', '1928', '1927'], dtype=object)

In [87]:
años_a_filtrar = [201, 2, 199, 2, 198, 2, 197, 196, 195, 194, 193, 193, 192, 191, 19, 189, 188, 187, 186, 185, 184, 183, 182, 181, 18, 178, 17, 158, '']
# Filtrar el DataFrame según los años en la lista
filas_años_incompletos = df[df['year'].isin(años_a_filtrar)]
indices_años_incompletos = filas_años_incompletos.index
indices_años_incompletos.tolist()

[]

In [88]:
df.drop([6177, 6178, 6179, 6180, 6181, 6182, 6183, 6184, 6185, 6186, 6187, 6188, 6189, 6190, 6191, 6192, 6193, 6194, 6195, 6196, 6197, 6198, 6199, 6200, 6201, 6202, 6203, 6204,
 6205, 6206, 6207, 6208, 6209, 6210, 6211, 6212, 6213, 6214, 6215, 6216, 6217, 6218, 6219, 6220, 6221, 6222, 6223, 6224, 6225, 6226, 6227, 6228, 6229, 6230, 6231, 6232, 6233,
 6234, 6235, 6236, 6237, 6238, 6239, 6240, 6241, 6242, 6243, 6244, 6245, 6246, 6247, 6248, 6249, 6250, 6251, 6252, 6253, 6254, 6255, 6256, 6257, 6258, 6259, 6260, 6261, 6262,
 6263, 6264, 6265, 6266, 6267, 6268, 6269, 6270, 6271, 6272, 6273, 6274, 6275, 6276, 6277, 6278, 6279, 6280, 6281, 6282, 6283, 6284, 6285, 6286, 6287, 6288, 6289, 6290, 6291,
 6292, 6293, 6294, 6295, 6296, 6297, 6298, 6299, 6300, 6301])

KeyError: '[6177, 6178, 6179, 6180, 6181, 6182, 6183, 6184, 6185, 6186, 6187, 6188, 6189, 6190, 6191, 6192, 6193, 6194, 6195, 6196, 6197, 6198, 6199, 6200, 6201, 6202, 6203, 6204, 6205, 6206, 6207, 6208, 6209, 6210, 6211, 6212, 6213, 6214, 6215, 6216, 6217, 6218, 6219, 6220, 6221, 6222, 6223, 6224, 6225, 6226, 6227, 6228, 6229, 6230, 6231, 6232, 6233, 6234, 6235, 6236, 6237, 6238, 6239, 6240, 6241, 6242, 6243, 6244, 6245, 6246, 6247, 6248, 6249, 6250, 6251, 6252, 6253, 6254, 6255, 6256, 6257, 6258, 6259, 6260, 6261, 6262, 6263, 6264, 6265, 6266, 6267, 6268, 6269, 6270, 6271, 6272, 6273, 6274, 6275, 6276, 6277, 6278, 6279, 6280, 6281, 6282, 6283, 6284, 6285, 6286, 6287, 6288, 6289, 6290, 6291, 6292, 6293, 6294, 6295, 6296, 6297, 6298, 6299, 6300, 6301] not found in axis'